package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.Date;

public class CCompania {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_COMPANIA.ID_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idCompania;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_COMPANIA.FECHA_ALTA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String fechaAlta;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_COMPANIA.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String nombre;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_COMPANIA.ID_COMPANIA
	 * @return  the value of C_COMPANIA.ID_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdCompania() {
		return idCompania;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_COMPANIA.ID_COMPANIA
	 * @param idCompania  the value for C_COMPANIA.ID_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdCompania(String idCompania) {
		this.idCompania = idCompania;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_COMPANIA.FECHA_ALTA
	 * @return  the value of C_COMPANIA.FECHA_ALTA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getFechaAlta() {
		return fechaAlta;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_COMPANIA.FECHA_ALTA
	 * @param fechaAlta  the value for C_COMPANIA.FECHA_ALTA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setFechaAlta(String fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_COMPANIA.NOMBRE
	 * @return  the value of C_COMPANIA.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_COMPANIA.NOMBRE
	 * @param nombre  the value for C_COMPANIA.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}