package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class CParametro {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PARAMETRO.ID_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idParametro;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PARAMETRO.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PARAMETRO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String descripcion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PARAMETRO.VALOR_NUMERICO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String valorNumerico;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PARAMETRO.VALOR_DECIMAL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String valorDecimal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PARAMETRO.VALOR_CADENA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String valorCadena;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PARAMETRO.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idEmisor;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PARAMETRO.ID_PARAMETRO
	 * @return  the value of C_PARAMETRO.ID_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdParametro() {
		return idParametro;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PARAMETRO.ID_PARAMETRO
	 * @param idParametro  the value for C_PARAMETRO.ID_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdParametro(String idParametro) {
		this.idParametro = idParametro;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PARAMETRO.NOMBRE
	 * @return  the value of C_PARAMETRO.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PARAMETRO.NOMBRE
	 * @param nombre  the value for C_PARAMETRO.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PARAMETRO.DESCRIPCION
	 * @return  the value of C_PARAMETRO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PARAMETRO.DESCRIPCION
	 * @param descripcion  the value for C_PARAMETRO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PARAMETRO.VALOR_NUMERICO
	 * @return  the value of C_PARAMETRO.VALOR_NUMERICO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getValorNumerico() {
		return valorNumerico;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PARAMETRO.VALOR_NUMERICO
	 * @param valorNumerico  the value for C_PARAMETRO.VALOR_NUMERICO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setValorNumerico(String valorNumerico) {
		this.valorNumerico = valorNumerico;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PARAMETRO.VALOR_DECIMAL
	 * @return  the value of C_PARAMETRO.VALOR_DECIMAL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getValorDecimal() {
		return valorDecimal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PARAMETRO.VALOR_DECIMAL
	 * @param valorDecimal  the value for C_PARAMETRO.VALOR_DECIMAL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setValorDecimal(String valorDecimal) {
		this.valorDecimal = valorDecimal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PARAMETRO.VALOR_CADENA
	 * @return  the value of C_PARAMETRO.VALOR_CADENA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getValorCadena() {
		return valorCadena;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PARAMETRO.VALOR_CADENA
	 * @param valorCadena  the value for C_PARAMETRO.VALOR_CADENA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setValorCadena(String valorCadena) {
		this.valorCadena = valorCadena;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PARAMETRO.ID_EMISOR
	 * @return  the value of C_PARAMETRO.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdEmisor() {
		return idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PARAMETRO.ID_EMISOR
	 * @param idEmisor  the value for C_PARAMETRO.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdEmisor(String idEmisor) {
		this.idEmisor = idEmisor;
	}
}