package mx.com.factmex.app.server.sqlmaps.model;

public class CPerfil {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PERFIL.ID_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idPerfil;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PERFIL.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_PERFIL.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PERFIL.ID_PERFIL
	 * @return  the value of C_PERFIL.ID_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdPerfil() {
		return idPerfil;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PERFIL.ID_PERFIL
	 * @param idPerfil  the value for C_PERFIL.ID_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdPerfil(String idPerfil) {
		this.idPerfil = idPerfil;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PERFIL.NOMBRE
	 * @return  the value of C_PERFIL.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PERFIL.NOMBRE
	 * @param nombre  the value for C_PERFIL.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_PERFIL.DESCRIPCION
	 * @return  the value of C_PERFIL.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_PERFIL.DESCRIPCION
	 * @param descripcion  the value for C_PERFIL.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}