package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class CTipoContacto {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_CONTACTO.ID_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idTipoContacto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_CONTACTO.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_CONTACTO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_CONTACTO.ID_TIPO_CONTACTO
	 * @return  the value of C_TIPO_CONTACTO.ID_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdTipoContacto() {
		return idTipoContacto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_CONTACTO.ID_TIPO_CONTACTO
	 * @param idTipoContacto  the value for C_TIPO_CONTACTO.ID_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdTipoContacto(String idTipoContacto) {
		this.idTipoContacto = idTipoContacto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_CONTACTO.NOMBRE
	 * @return  the value of C_TIPO_CONTACTO.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_CONTACTO.NOMBRE
	 * @param nombre  the value for C_TIPO_CONTACTO.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_CONTACTO.DESCRIPCION
	 * @return  the value of C_TIPO_CONTACTO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_CONTACTO.DESCRIPCION
	 * @param descripcion  the value for C_TIPO_CONTACTO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}