package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class CTipoPersona {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_PERSONA.ID_TIPO_PERSONA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idTipoPersona;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_PERSONA.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_PERSONA.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_PERSONA.ID_TIPO_PERSONA
	 * @return  the value of C_TIPO_PERSONA.ID_TIPO_PERSONA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdTipoPersona() {
		return idTipoPersona;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_PERSONA.ID_TIPO_PERSONA
	 * @param idTipoPersona  the value for C_TIPO_PERSONA.ID_TIPO_PERSONA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdTipoPersona(String idTipoPersona) {
		this.idTipoPersona = idTipoPersona;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_PERSONA.NOMBRE
	 * @return  the value of C_TIPO_PERSONA.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_PERSONA.NOMBRE
	 * @param nombre  the value for C_TIPO_PERSONA.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_PERSONA.DESCRIPCION
	 * @return  the value of C_TIPO_PERSONA.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_PERSONA.DESCRIPCION
	 * @param descripcion  the value for C_TIPO_PERSONA.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}