package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class CTipoComprobante {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idTipoComprobante;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_COMPROBANTE.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_COMPROBANTE.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @return  the value of C_TIPO_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdTipoComprobante() {
		return idTipoComprobante;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @param idTipoComprobante  the value for C_TIPO_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdTipoComprobante(String idTipoComprobante) {
		this.idTipoComprobante = idTipoComprobante;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_COMPROBANTE.NOMBRE
	 * @return  the value of C_TIPO_COMPROBANTE.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_COMPROBANTE.NOMBRE
	 * @param nombre  the value for C_TIPO_COMPROBANTE.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_COMPROBANTE.DESCRIPCION
	 * @return  the value of C_TIPO_COMPROBANTE.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_COMPROBANTE.DESCRIPCION
	 * @param descripcion  the value for C_TIPO_COMPROBANTE.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}