package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class CTipoDireccion {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_DIRECCION.ID_TIPO_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idTipoDireccion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_DIRECCION.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column C_TIPO_DIRECCION.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_DIRECCION.ID_TIPO_DIRECCION
	 * @return  the value of C_TIPO_DIRECCION.ID_TIPO_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdTipoDireccion() {
		return idTipoDireccion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_DIRECCION.ID_TIPO_DIRECCION
	 * @param idTipoDireccion  the value for C_TIPO_DIRECCION.ID_TIPO_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdTipoDireccion(String idTipoDireccion) {
		this.idTipoDireccion = idTipoDireccion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_DIRECCION.NOMBRE
	 * @return  the value of C_TIPO_DIRECCION.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_DIRECCION.NOMBRE
	 * @param nombre  the value for C_TIPO_DIRECCION.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column C_TIPO_DIRECCION.DESCRIPCION
	 * @return  the value of C_TIPO_DIRECCION.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column C_TIPO_DIRECCION.DESCRIPCION
	 * @param descripcion  the value for C_TIPO_DIRECCION.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}