package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class TCliente {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CLIENTE.ID_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idCliente;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CLIENTE.RFC
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String rfc;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CLIENTE.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CLIENTE.ID_TIPO_PERSONA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idTipoPersona;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CLIENTE.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idEmisor;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CLIENTE.ID_CLIENTE
	 * @return  the value of T_CLIENTE.ID_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdCliente() {
		return idCliente;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CLIENTE.ID_CLIENTE
	 * @param idCliente  the value for T_CLIENTE.ID_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CLIENTE.RFC
	 * @return  the value of T_CLIENTE.RFC
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getRfc() {
		return rfc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CLIENTE.RFC
	 * @param rfc  the value for T_CLIENTE.RFC
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CLIENTE.NOMBRE
	 * @return  the value of T_CLIENTE.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CLIENTE.NOMBRE
	 * @param nombre  the value for T_CLIENTE.NOMBRE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CLIENTE.ID_TIPO_PERSONA
	 * @return  the value of T_CLIENTE.ID_TIPO_PERSONA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdTipoPersona() {
		return idTipoPersona;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CLIENTE.ID_TIPO_PERSONA
	 * @param idTipoPersona  the value for T_CLIENTE.ID_TIPO_PERSONA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdTipoPersona(String idTipoPersona) {
		this.idTipoPersona = idTipoPersona;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CLIENTE.ID_EMISOR
	 * @return  the value of T_CLIENTE.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdEmisor() {
		return idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CLIENTE.ID_EMISOR
	 * @param idEmisor  the value for T_CLIENTE.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdEmisor(String idEmisor) {
		this.idEmisor = idEmisor;
	}
}