package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TClienteExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public TClienteExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected TClienteExample(TClienteExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdClienteIsNull() {
			addCriterion("ID_CLIENTE is null");
			return this;
		}

		public Criteria andIdClienteIsNotNull() {
			addCriterion("ID_CLIENTE is not null");
			return this;
		}

		public Criteria andIdClienteEqualTo(String value) {
			addCriterion("ID_CLIENTE =", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotEqualTo(String value) {
			addCriterion("ID_CLIENTE <>", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteGreaterThan(String value) {
			addCriterion("ID_CLIENTE >", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteGreaterThanOrEqualTo(String value) {
			addCriterion("ID_CLIENTE >=", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLessThan(String value) {
			addCriterion("ID_CLIENTE <", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLessThanOrEqualTo(String value) {
			addCriterion("ID_CLIENTE <=", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLike(String value) {
			addCriterion("ID_CLIENTE like", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotLike(String value) {
			addCriterion("ID_CLIENTE not like", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteIn(List values) {
			addCriterion("ID_CLIENTE in", values, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotIn(List values) {
			addCriterion("ID_CLIENTE not in", values, "idCliente");
			return this;
		}

		public Criteria andIdClienteBetween(String value1, String value2) {
			addCriterion("ID_CLIENTE between", value1, value2, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotBetween(String value1, String value2) {
			addCriterion("ID_CLIENTE not between", value1, value2, "idCliente");
			return this;
		}

		public Criteria andRfcIsNull() {
			addCriterion("RFC is null");
			return this;
		}

		public Criteria andRfcIsNotNull() {
			addCriterion("RFC is not null");
			return this;
		}

		public Criteria andRfcEqualTo(String value) {
			addCriterion("RFC =", value, "rfc");
			return this;
		}

		public Criteria andRfcNotEqualTo(String value) {
			addCriterion("RFC <>", value, "rfc");
			return this;
		}

		public Criteria andRfcGreaterThan(String value) {
			addCriterion("RFC >", value, "rfc");
			return this;
		}

		public Criteria andRfcGreaterThanOrEqualTo(String value) {
			addCriterion("RFC >=", value, "rfc");
			return this;
		}

		public Criteria andRfcLessThan(String value) {
			addCriterion("RFC <", value, "rfc");
			return this;
		}

		public Criteria andRfcLessThanOrEqualTo(String value) {
			addCriterion("RFC <=", value, "rfc");
			return this;
		}

		public Criteria andRfcLike(String value) {
			addCriterion("RFC like", value, "rfc");
			return this;
		}

		public Criteria andRfcNotLike(String value) {
			addCriterion("RFC not like", value, "rfc");
			return this;
		}

		public Criteria andRfcIn(List values) {
			addCriterion("RFC in", values, "rfc");
			return this;
		}

		public Criteria andRfcNotIn(List values) {
			addCriterion("RFC not in", values, "rfc");
			return this;
		}

		public Criteria andRfcBetween(String value1, String value2) {
			addCriterion("RFC between", value1, value2, "rfc");
			return this;
		}

		public Criteria andRfcNotBetween(String value1, String value2) {
			addCriterion("RFC not between", value1, value2, "rfc");
			return this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("NOMBRE is null");
			return this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("NOMBRE is not null");
			return this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("NOMBRE =", value, "nombre");
			return this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("NOMBRE <>", value, "nombre");
			return this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("NOMBRE >", value, "nombre");
			return this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE >=", value, "nombre");
			return this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("NOMBRE <", value, "nombre");
			return this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE <=", value, "nombre");
			return this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("NOMBRE like", value, "nombre");
			return this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("NOMBRE not like", value, "nombre");
			return this;
		}

		public Criteria andNombreIn(List values) {
			addCriterion("NOMBRE in", values, "nombre");
			return this;
		}

		public Criteria andNombreNotIn(List values) {
			addCriterion("NOMBRE not in", values, "nombre");
			return this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("NOMBRE between", value1, value2, "nombre");
			return this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("NOMBRE not between", value1, value2, "nombre");
			return this;
		}

		public Criteria andIdTipoPersonaIsNull() {
			addCriterion("ID_TIPO_PERSONA is null");
			return this;
		}

		public Criteria andIdTipoPersonaIsNotNull() {
			addCriterion("ID_TIPO_PERSONA is not null");
			return this;
		}

		public Criteria andIdTipoPersonaEqualTo(String value) {
			addCriterion("ID_TIPO_PERSONA =", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaNotEqualTo(String value) {
			addCriterion("ID_TIPO_PERSONA <>", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaGreaterThan(String value) {
			addCriterion("ID_TIPO_PERSONA >", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaGreaterThanOrEqualTo(String value) {
			addCriterion("ID_TIPO_PERSONA >=", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaLessThan(String value) {
			addCriterion("ID_TIPO_PERSONA <", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaLessThanOrEqualTo(String value) {
			addCriterion("ID_TIPO_PERSONA <=", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaLike(String value) {
			addCriterion("ID_TIPO_PERSONA like", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaNotLike(String value) {
			addCriterion("ID_TIPO_PERSONA not like", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaIn(List values) {
			addCriterion("ID_TIPO_PERSONA in", values, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaNotIn(List values) {
			addCriterion("ID_TIPO_PERSONA not in", values, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaBetween(String value1, String value2) {
			addCriterion("ID_TIPO_PERSONA between", value1, value2,
					"idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaNotBetween(String value1, String value2) {
			addCriterion("ID_TIPO_PERSONA not between", value1, value2,
					"idTipoPersona");
			return this;
		}

		public Criteria andIdEmisorIsNull() {
			addCriterion("ID_EMISOR is null");
			return this;
		}

		public Criteria andIdEmisorIsNotNull() {
			addCriterion("ID_EMISOR is not null");
			return this;
		}

		public Criteria andIdEmisorEqualTo(String value) {
			addCriterion("ID_EMISOR =", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotEqualTo(String value) {
			addCriterion("ID_EMISOR <>", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThan(String value) {
			addCriterion("ID_EMISOR >", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR >=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThan(String value) {
			addCriterion("ID_EMISOR <", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR <=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLike(String value) {
			addCriterion("ID_EMISOR like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotLike(String value) {
			addCriterion("ID_EMISOR not like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorIn(List values) {
			addCriterion("ID_EMISOR in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotIn(List values) {
			addCriterion("ID_EMISOR not in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorBetween(String value1, String value2) {
			addCriterion("ID_EMISOR between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotBetween(String value1, String value2) {
			addCriterion("ID_EMISOR not between", value1, value2, "idEmisor");
			return this;
		}
	}
}