package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.Date;

public class TComprobante {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.ID_FACTURA
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String idFactura;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.FOLIO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String folio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.FECHA
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String fecha;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.FACTURADO_A
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String facturadoA;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.MONTO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String monto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.ID_ESTATUS
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String idEstatus;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String idTipoComprobante;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.ID_EMISOR
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String idEmisor;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.ID_CLIENTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String idCliente;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.NOMBRE_ARCHIVO_XML
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String nombreArchivoXml;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.ESTATUS_SAT
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String estatusSat;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.ANIO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String anio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_COMPROBANTE.MES
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private String mes;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.ID_FACTURA
	 * @return  the value of T_COMPROBANTE.ID_FACTURA
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getIdFactura() {
		return idFactura;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.ID_FACTURA
	 * @param idFactura  the value for T_COMPROBANTE.ID_FACTURA
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setIdFactura(String idFactura) {
		this.idFactura = idFactura;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.FOLIO
	 * @return  the value of T_COMPROBANTE.FOLIO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getFolio() {
		return folio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.FOLIO
	 * @param folio  the value for T_COMPROBANTE.FOLIO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setFolio(String folio) {
		this.folio = folio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.FECHA
	 * @return  the value of T_COMPROBANTE.FECHA
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getFecha() {
		return fecha;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.FECHA
	 * @param fecha  the value for T_COMPROBANTE.FECHA
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.FACTURADO_A
	 * @return  the value of T_COMPROBANTE.FACTURADO_A
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getFacturadoA() {
		return facturadoA;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.FACTURADO_A
	 * @param facturadoA  the value for T_COMPROBANTE.FACTURADO_A
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setFacturadoA(String facturadoA) {
		this.facturadoA = facturadoA;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.MONTO
	 * @return  the value of T_COMPROBANTE.MONTO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getMonto() {
		return monto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.MONTO
	 * @param monto  the value for T_COMPROBANTE.MONTO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setMonto(String monto) {
		this.monto = monto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.ID_ESTATUS
	 * @return  the value of T_COMPROBANTE.ID_ESTATUS
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getIdEstatus() {
		return idEstatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.ID_ESTATUS
	 * @param idEstatus  the value for T_COMPROBANTE.ID_ESTATUS
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setIdEstatus(String idEstatus) {
		this.idEstatus = idEstatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @return  the value of T_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getIdTipoComprobante() {
		return idTipoComprobante;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @param idTipoComprobante  the value for T_COMPROBANTE.ID_TIPO_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setIdTipoComprobante(String idTipoComprobante) {
		this.idTipoComprobante = idTipoComprobante;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.ID_EMISOR
	 * @return  the value of T_COMPROBANTE.ID_EMISOR
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getIdEmisor() {
		return idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.ID_EMISOR
	 * @param idEmisor  the value for T_COMPROBANTE.ID_EMISOR
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setIdEmisor(String idEmisor) {
		this.idEmisor = idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.ID_CLIENTE
	 * @return  the value of T_COMPROBANTE.ID_CLIENTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getIdCliente() {
		return idCliente;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.ID_CLIENTE
	 * @param idCliente  the value for T_COMPROBANTE.ID_CLIENTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.NOMBRE_ARCHIVO_XML
	 * @return  the value of T_COMPROBANTE.NOMBRE_ARCHIVO_XML
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getNombreArchivoXml() {
		return nombreArchivoXml;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.NOMBRE_ARCHIVO_XML
	 * @param nombreArchivoXml  the value for T_COMPROBANTE.NOMBRE_ARCHIVO_XML
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setNombreArchivoXml(String nombreArchivoXml) {
		this.nombreArchivoXml = nombreArchivoXml;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.ESTATUS_SAT
	 * @return  the value of T_COMPROBANTE.ESTATUS_SAT
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getEstatusSat() {
		return estatusSat;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.ESTATUS_SAT
	 * @param estatusSat  the value for T_COMPROBANTE.ESTATUS_SAT
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setEstatusSat(String estatusSat) {
		this.estatusSat = estatusSat;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.ANIO
	 * @return  the value of T_COMPROBANTE.ANIO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getAnio() {
		return anio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.ANIO
	 * @param anio  the value for T_COMPROBANTE.ANIO
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setAnio(String anio) {
		this.anio = anio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_COMPROBANTE.MES
	 * @return  the value of T_COMPROBANTE.MES
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getMes() {
		return mes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_COMPROBANTE.MES
	 * @param mes  the value for T_COMPROBANTE.MES
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setMes(String mes) {
		this.mes = mes;
	}
}