package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TComprobanteExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public TComprobanteExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	protected TComprobanteExample(TComprobanteExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdFacturaIsNull() {
			addCriterion("ID_FACTURA is null");
			return this;
		}

		public Criteria andIdFacturaIsNotNull() {
			addCriterion("ID_FACTURA is not null");
			return this;
		}

		public Criteria andIdFacturaEqualTo(String value) {
			addCriterion("ID_FACTURA =", value, "idFactura");
			return this;
		}

		public Criteria andIdFacturaNotEqualTo(String value) {
			addCriterion("ID_FACTURA <>", value, "idFactura");
			return this;
		}

		public Criteria andIdFacturaGreaterThan(String value) {
			addCriterion("ID_FACTURA >", value, "idFactura");
			return this;
		}

		public Criteria andIdFacturaGreaterThanOrEqualTo(String value) {
			addCriterion("ID_FACTURA >=", value, "idFactura");
			return this;
		}

		public Criteria andIdFacturaLessThan(String value) {
			addCriterion("ID_FACTURA <", value, "idFactura");
			return this;
		}

		public Criteria andIdFacturaLessThanOrEqualTo(String value) {
			addCriterion("ID_FACTURA <=", value, "idFactura");
			return this;
		}

		public Criteria andIdFacturaLike(String value) {
			addCriterion("ID_FACTURA like", value, "idFactura");
			return this;
		}

		public Criteria andIdFacturaNotLike(String value) {
			addCriterion("ID_FACTURA not like", value, "idFactura");
			return this;
		}

		public Criteria andIdFacturaIn(List values) {
			addCriterion("ID_FACTURA in", values, "idFactura");
			return this;
		}

		public Criteria andIdFacturaNotIn(List values) {
			addCriterion("ID_FACTURA not in", values, "idFactura");
			return this;
		}

		public Criteria andIdFacturaBetween(String value1, String value2) {
			addCriterion("ID_FACTURA between", value1, value2, "idFactura");
			return this;
		}

		public Criteria andIdFacturaNotBetween(String value1, String value2) {
			addCriterion("ID_FACTURA not between", value1, value2, "idFactura");
			return this;
		}

		public Criteria andFolioIsNull() {
			addCriterion("FOLIO is null");
			return this;
		}

		public Criteria andFolioIsNotNull() {
			addCriterion("FOLIO is not null");
			return this;
		}

		public Criteria andFolioEqualTo(String value) {
			addCriterion("FOLIO =", value, "folio");
			return this;
		}

		public Criteria andFolioNotEqualTo(String value) {
			addCriterion("FOLIO <>", value, "folio");
			return this;
		}

		public Criteria andFolioGreaterThan(String value) {
			addCriterion("FOLIO >", value, "folio");
			return this;
		}

		public Criteria andFolioGreaterThanOrEqualTo(String value) {
			addCriterion("FOLIO >=", value, "folio");
			return this;
		}

		public Criteria andFolioLessThan(String value) {
			addCriterion("FOLIO <", value, "folio");
			return this;
		}

		public Criteria andFolioLessThanOrEqualTo(String value) {
			addCriterion("FOLIO <=", value, "folio");
			return this;
		}

		public Criteria andFolioLike(String value) {
			addCriterion("FOLIO like", value, "folio");
			return this;
		}

		public Criteria andFolioNotLike(String value) {
			addCriterion("FOLIO not like", value, "folio");
			return this;
		}

		public Criteria andFolioIn(List values) {
			addCriterion("FOLIO in", values, "folio");
			return this;
		}

		public Criteria andFolioNotIn(List values) {
			addCriterion("FOLIO not in", values, "folio");
			return this;
		}

		public Criteria andFolioBetween(String value1, String value2) {
			addCriterion("FOLIO between", value1, value2, "folio");
			return this;
		}

		public Criteria andFolioNotBetween(String value1, String value2) {
			addCriterion("FOLIO not between", value1, value2, "folio");
			return this;
		}

		public Criteria andFechaIsNull() {
			addCriterion("FECHA is null");
			return this;
		}

		public Criteria andFechaIsNotNull() {
			addCriterion("FECHA is not null");
			return this;
		}

		public Criteria andFechaEqualTo(String value) {
			addCriterion("FECHA =", value, "fecha");
			return this;
		}

		public Criteria andFechaNotEqualTo(String value) {
			addCriterion("FECHA <>", value, "fecha");
			return this;
		}

		public Criteria andFechaGreaterThan(String value) {
			addCriterion("FECHA >", value, "fecha");
			return this;
		}

		public Criteria andFechaGreaterThanOrEqualTo(String value) {
			addCriterion("FECHA >=", value, "fecha");
			return this;
		}

		public Criteria andFechaLessThan(String value) {
			addCriterion("FECHA <", value, "fecha");
			return this;
		}

		public Criteria andFechaLessThanOrEqualTo(String value) {
			addCriterion("FECHA <=", value, "fecha");
			return this;
		}

		public Criteria andFechaLike(String value) {
			addCriterion("FECHA like", value, "fecha");
			return this;
		}

		public Criteria andFechaNotLike(String value) {
			addCriterion("FECHA not like", value, "fecha");
			return this;
		}

		public Criteria andFechaIn(List values) {
			addCriterion("FECHA in", values, "fecha");
			return this;
		}

		public Criteria andFechaNotIn(List values) {
			addCriterion("FECHA not in", values, "fecha");
			return this;
		}

		public Criteria andFechaBetween(String value1, String value2) {
			addCriterion("FECHA between", value1, value2, "fecha");
			return this;
		}

		public Criteria andFechaNotBetween(String value1, String value2) {
			addCriterion("FECHA not between", value1, value2, "fecha");
			return this;
		}

		public Criteria andFacturadoAIsNull() {
			addCriterion("FACTURADO_A is null");
			return this;
		}

		public Criteria andFacturadoAIsNotNull() {
			addCriterion("FACTURADO_A is not null");
			return this;
		}

		public Criteria andFacturadoAEqualTo(String value) {
			addCriterion("FACTURADO_A =", value, "facturadoA");
			return this;
		}

		public Criteria andFacturadoANotEqualTo(String value) {
			addCriterion("FACTURADO_A <>", value, "facturadoA");
			return this;
		}

		public Criteria andFacturadoAGreaterThan(String value) {
			addCriterion("FACTURADO_A >", value, "facturadoA");
			return this;
		}

		public Criteria andFacturadoAGreaterThanOrEqualTo(String value) {
			addCriterion("FACTURADO_A >=", value, "facturadoA");
			return this;
		}

		public Criteria andFacturadoALessThan(String value) {
			addCriterion("FACTURADO_A <", value, "facturadoA");
			return this;
		}

		public Criteria andFacturadoALessThanOrEqualTo(String value) {
			addCriterion("FACTURADO_A <=", value, "facturadoA");
			return this;
		}

		public Criteria andFacturadoALike(String value) {
			addCriterion("FACTURADO_A like", value, "facturadoA");
			return this;
		}

		public Criteria andFacturadoANotLike(String value) {
			addCriterion("FACTURADO_A not like", value, "facturadoA");
			return this;
		}

		public Criteria andFacturadoAIn(List values) {
			addCriterion("FACTURADO_A in", values, "facturadoA");
			return this;
		}

		public Criteria andFacturadoANotIn(List values) {
			addCriterion("FACTURADO_A not in", values, "facturadoA");
			return this;
		}

		public Criteria andFacturadoABetween(String value1, String value2) {
			addCriterion("FACTURADO_A between", value1, value2, "facturadoA");
			return this;
		}

		public Criteria andFacturadoANotBetween(String value1, String value2) {
			addCriterion("FACTURADO_A not between", value1, value2,
					"facturadoA");
			return this;
		}

		public Criteria andMontoIsNull() {
			addCriterion("MONTO is null");
			return this;
		}

		public Criteria andMontoIsNotNull() {
			addCriterion("MONTO is not null");
			return this;
		}

		public Criteria andMontoEqualTo(String value) {
			addCriterion("MONTO =", value, "monto");
			return this;
		}

		public Criteria andMontoNotEqualTo(String value) {
			addCriterion("MONTO <>", value, "monto");
			return this;
		}

		public Criteria andMontoGreaterThan(String value) {
			addCriterion("MONTO >", value, "monto");
			return this;
		}

		public Criteria andMontoGreaterThanOrEqualTo(String value) {
			addCriterion("MONTO >=", value, "monto");
			return this;
		}

		public Criteria andMontoLessThan(String value) {
			addCriterion("MONTO <", value, "monto");
			return this;
		}

		public Criteria andMontoLessThanOrEqualTo(String value) {
			addCriterion("MONTO <=", value, "monto");
			return this;
		}

		public Criteria andMontoLike(String value) {
			addCriterion("MONTO like", value, "monto");
			return this;
		}

		public Criteria andMontoNotLike(String value) {
			addCriterion("MONTO not like", value, "monto");
			return this;
		}

		public Criteria andMontoIn(List values) {
			addCriterion("MONTO in", values, "monto");
			return this;
		}

		public Criteria andMontoNotIn(List values) {
			addCriterion("MONTO not in", values, "monto");
			return this;
		}

		public Criteria andMontoBetween(String value1, String value2) {
			addCriterion("MONTO between", value1, value2, "monto");
			return this;
		}

		public Criteria andMontoNotBetween(String value1, String value2) {
			addCriterion("MONTO not between", value1, value2, "monto");
			return this;
		}

		public Criteria andIdEstatusIsNull() {
			addCriterion("ID_ESTATUS is null");
			return this;
		}

		public Criteria andIdEstatusIsNotNull() {
			addCriterion("ID_ESTATUS is not null");
			return this;
		}

		public Criteria andIdEstatusEqualTo(String value) {
			addCriterion("ID_ESTATUS =", value, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusNotEqualTo(String value) {
			addCriterion("ID_ESTATUS <>", value, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusGreaterThan(String value) {
			addCriterion("ID_ESTATUS >", value, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusGreaterThanOrEqualTo(String value) {
			addCriterion("ID_ESTATUS >=", value, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusLessThan(String value) {
			addCriterion("ID_ESTATUS <", value, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusLessThanOrEqualTo(String value) {
			addCriterion("ID_ESTATUS <=", value, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusLike(String value) {
			addCriterion("ID_ESTATUS like", value, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusNotLike(String value) {
			addCriterion("ID_ESTATUS not like", value, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusIn(List values) {
			addCriterion("ID_ESTATUS in", values, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusNotIn(List values) {
			addCriterion("ID_ESTATUS not in", values, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusBetween(String value1, String value2) {
			addCriterion("ID_ESTATUS between", value1, value2, "idEstatus");
			return this;
		}

		public Criteria andIdEstatusNotBetween(String value1, String value2) {
			addCriterion("ID_ESTATUS not between", value1, value2, "idEstatus");
			return this;
		}

		public Criteria andIdTipoComprobanteIsNull() {
			addCriterion("ID_TIPO_COMPROBANTE is null");
			return this;
		}

		public Criteria andIdTipoComprobanteIsNotNull() {
			addCriterion("ID_TIPO_COMPROBANTE is not null");
			return this;
		}

		public Criteria andIdTipoComprobanteEqualTo(String value) {
			addCriterion("ID_TIPO_COMPROBANTE =", value, "idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteNotEqualTo(String value) {
			addCriterion("ID_TIPO_COMPROBANTE <>", value, "idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteGreaterThan(String value) {
			addCriterion("ID_TIPO_COMPROBANTE >", value, "idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteGreaterThanOrEqualTo(String value) {
			addCriterion("ID_TIPO_COMPROBANTE >=", value, "idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteLessThan(String value) {
			addCriterion("ID_TIPO_COMPROBANTE <", value, "idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteLessThanOrEqualTo(String value) {
			addCriterion("ID_TIPO_COMPROBANTE <=", value, "idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteLike(String value) {
			addCriterion("ID_TIPO_COMPROBANTE like", value, "idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteNotLike(String value) {
			addCriterion("ID_TIPO_COMPROBANTE not like", value,
					"idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteIn(List values) {
			addCriterion("ID_TIPO_COMPROBANTE in", values, "idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteNotIn(List values) {
			addCriterion("ID_TIPO_COMPROBANTE not in", values,
					"idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteBetween(String value1, String value2) {
			addCriterion("ID_TIPO_COMPROBANTE between", value1, value2,
					"idTipoComprobante");
			return this;
		}

		public Criteria andIdTipoComprobanteNotBetween(String value1,
				String value2) {
			addCriterion("ID_TIPO_COMPROBANTE not between", value1, value2,
					"idTipoComprobante");
			return this;
		}

		public Criteria andIdEmisorIsNull() {
			addCriterion("ID_EMISOR is null");
			return this;
		}

		public Criteria andIdEmisorIsNotNull() {
			addCriterion("ID_EMISOR is not null");
			return this;
		}

		public Criteria andIdEmisorEqualTo(String value) {
			addCriterion("ID_EMISOR =", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotEqualTo(String value) {
			addCriterion("ID_EMISOR <>", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThan(String value) {
			addCriterion("ID_EMISOR >", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR >=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThan(String value) {
			addCriterion("ID_EMISOR <", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR <=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLike(String value) {
			addCriterion("ID_EMISOR like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotLike(String value) {
			addCriterion("ID_EMISOR not like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorIn(List values) {
			addCriterion("ID_EMISOR in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotIn(List values) {
			addCriterion("ID_EMISOR not in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorBetween(String value1, String value2) {
			addCriterion("ID_EMISOR between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotBetween(String value1, String value2) {
			addCriterion("ID_EMISOR not between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andIdClienteIsNull() {
			addCriterion("ID_CLIENTE is null");
			return this;
		}

		public Criteria andIdClienteIsNotNull() {
			addCriterion("ID_CLIENTE is not null");
			return this;
		}

		public Criteria andIdClienteEqualTo(String value) {
			addCriterion("ID_CLIENTE =", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotEqualTo(String value) {
			addCriterion("ID_CLIENTE <>", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteGreaterThan(String value) {
			addCriterion("ID_CLIENTE >", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteGreaterThanOrEqualTo(String value) {
			addCriterion("ID_CLIENTE >=", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLessThan(String value) {
			addCriterion("ID_CLIENTE <", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLessThanOrEqualTo(String value) {
			addCriterion("ID_CLIENTE <=", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLike(String value) {
			addCriterion("ID_CLIENTE like", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotLike(String value) {
			addCriterion("ID_CLIENTE not like", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteIn(List values) {
			addCriterion("ID_CLIENTE in", values, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotIn(List values) {
			addCriterion("ID_CLIENTE not in", values, "idCliente");
			return this;
		}

		public Criteria andIdClienteBetween(String value1, String value2) {
			addCriterion("ID_CLIENTE between", value1, value2, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotBetween(String value1, String value2) {
			addCriterion("ID_CLIENTE not between", value1, value2, "idCliente");
			return this;
		}

		public Criteria andNombreArchivoXmlIsNull() {
			addCriterion("NOMBRE_ARCHIVO_XML is null");
			return this;
		}

		public Criteria andNombreArchivoXmlIsNotNull() {
			addCriterion("NOMBRE_ARCHIVO_XML is not null");
			return this;
		}

		public Criteria andNombreArchivoXmlEqualTo(String value) {
			addCriterion("NOMBRE_ARCHIVO_XML =", value, "nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlNotEqualTo(String value) {
			addCriterion("NOMBRE_ARCHIVO_XML <>", value, "nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlGreaterThan(String value) {
			addCriterion("NOMBRE_ARCHIVO_XML >", value, "nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE_ARCHIVO_XML >=", value, "nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlLessThan(String value) {
			addCriterion("NOMBRE_ARCHIVO_XML <", value, "nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE_ARCHIVO_XML <=", value, "nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlLike(String value) {
			addCriterion("NOMBRE_ARCHIVO_XML like", value, "nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlNotLike(String value) {
			addCriterion("NOMBRE_ARCHIVO_XML not like", value,
					"nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlIn(List values) {
			addCriterion("NOMBRE_ARCHIVO_XML in", values, "nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlNotIn(List values) {
			addCriterion("NOMBRE_ARCHIVO_XML not in", values,
					"nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlBetween(String value1, String value2) {
			addCriterion("NOMBRE_ARCHIVO_XML between", value1, value2,
					"nombreArchivoXml");
			return this;
		}

		public Criteria andNombreArchivoXmlNotBetween(String value1,
				String value2) {
			addCriterion("NOMBRE_ARCHIVO_XML not between", value1, value2,
					"nombreArchivoXml");
			return this;
		}

		public Criteria andEstatusSatIsNull() {
			addCriterion("ESTATUS_SAT is null");
			return this;
		}

		public Criteria andEstatusSatIsNotNull() {
			addCriterion("ESTATUS_SAT is not null");
			return this;
		}

		public Criteria andEstatusSatEqualTo(String value) {
			addCriterion("ESTATUS_SAT =", value, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatNotEqualTo(String value) {
			addCriterion("ESTATUS_SAT <>", value, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatGreaterThan(String value) {
			addCriterion("ESTATUS_SAT >", value, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatGreaterThanOrEqualTo(String value) {
			addCriterion("ESTATUS_SAT >=", value, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatLessThan(String value) {
			addCriterion("ESTATUS_SAT <", value, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatLessThanOrEqualTo(String value) {
			addCriterion("ESTATUS_SAT <=", value, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatLike(String value) {
			addCriterion("ESTATUS_SAT like", value, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatNotLike(String value) {
			addCriterion("ESTATUS_SAT not like", value, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatIn(List values) {
			addCriterion("ESTATUS_SAT in", values, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatNotIn(List values) {
			addCriterion("ESTATUS_SAT not in", values, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatBetween(String value1, String value2) {
			addCriterion("ESTATUS_SAT between", value1, value2, "estatusSat");
			return this;
		}

		public Criteria andEstatusSatNotBetween(String value1, String value2) {
			addCriterion("ESTATUS_SAT not between", value1, value2,
					"estatusSat");
			return this;
		}

		public Criteria andAnioIsNull() {
			addCriterion("ANIO is null");
			return this;
		}

		public Criteria andAnioIsNotNull() {
			addCriterion("ANIO is not null");
			return this;
		}

		public Criteria andAnioEqualTo(String value) {
			addCriterion("ANIO =", value, "anio");
			return this;
		}

		public Criteria andAnioNotEqualTo(String value) {
			addCriterion("ANIO <>", value, "anio");
			return this;
		}

		public Criteria andAnioGreaterThan(String value) {
			addCriterion("ANIO >", value, "anio");
			return this;
		}

		public Criteria andAnioGreaterThanOrEqualTo(String value) {
			addCriterion("ANIO >=", value, "anio");
			return this;
		}

		public Criteria andAnioLessThan(String value) {
			addCriterion("ANIO <", value, "anio");
			return this;
		}

		public Criteria andAnioLessThanOrEqualTo(String value) {
			addCriterion("ANIO <=", value, "anio");
			return this;
		}

		public Criteria andAnioLike(String value) {
			addCriterion("ANIO like", value, "anio");
			return this;
		}

		public Criteria andAnioNotLike(String value) {
			addCriterion("ANIO not like", value, "anio");
			return this;
		}

		public Criteria andAnioIn(List values) {
			addCriterion("ANIO in", values, "anio");
			return this;
		}

		public Criteria andAnioNotIn(List values) {
			addCriterion("ANIO not in", values, "anio");
			return this;
		}

		public Criteria andAnioBetween(String value1, String value2) {
			addCriterion("ANIO between", value1, value2, "anio");
			return this;
		}

		public Criteria andAnioNotBetween(String value1, String value2) {
			addCriterion("ANIO not between", value1, value2, "anio");
			return this;
		}

		public Criteria andMesIsNull() {
			addCriterion("MES is null");
			return this;
		}

		public Criteria andMesIsNotNull() {
			addCriterion("MES is not null");
			return this;
		}

		public Criteria andMesEqualTo(String value) {
			addCriterion("MES =", value, "mes");
			return this;
		}

		public Criteria andMesNotEqualTo(String value) {
			addCriterion("MES <>", value, "mes");
			return this;
		}

		public Criteria andMesGreaterThan(String value) {
			addCriterion("MES >", value, "mes");
			return this;
		}

		public Criteria andMesGreaterThanOrEqualTo(String value) {
			addCriterion("MES >=", value, "mes");
			return this;
		}

		public Criteria andMesLessThan(String value) {
			addCriterion("MES <", value, "mes");
			return this;
		}

		public Criteria andMesLessThanOrEqualTo(String value) {
			addCriterion("MES <=", value, "mes");
			return this;
		}

		public Criteria andMesLike(String value) {
			addCriterion("MES like", value, "mes");
			return this;
		}

		public Criteria andMesNotLike(String value) {
			addCriterion("MES not like", value, "mes");
			return this;
		}

		public Criteria andMesIn(List values) {
			addCriterion("MES in", values, "mes");
			return this;
		}

		public Criteria andMesNotIn(List values) {
			addCriterion("MES not in", values, "mes");
			return this;
		}

		public Criteria andMesBetween(String value1, String value2) {
			addCriterion("MES between", value1, value2, "mes");
			return this;
		}

		public Criteria andMesNotBetween(String value1, String value2) {
			addCriterion("MES not between", value1, value2, "mes");
			return this;
		}
	}
}