package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class TContacto {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CONTACTO.ID_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idContacto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CONTACTO.CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String contacto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CONTACTO.ID_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idTipoContacto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_CONTACTO.ID_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idDireccion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CONTACTO.ID_CONTACTO
	 * @return  the value of T_CONTACTO.ID_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdContacto() {
		return idContacto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CONTACTO.ID_CONTACTO
	 * @param idContacto  the value for T_CONTACTO.ID_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdContacto(String idContacto) {
		this.idContacto = idContacto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CONTACTO.CONTACTO
	 * @return  the value of T_CONTACTO.CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getContacto() {
		return contacto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CONTACTO.CONTACTO
	 * @param contacto  the value for T_CONTACTO.CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CONTACTO.ID_TIPO_CONTACTO
	 * @return  the value of T_CONTACTO.ID_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdTipoContacto() {
		return idTipoContacto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CONTACTO.ID_TIPO_CONTACTO
	 * @param idTipoContacto  the value for T_CONTACTO.ID_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdTipoContacto(String idTipoContacto) {
		this.idTipoContacto = idTipoContacto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_CONTACTO.ID_DIRECCION
	 * @return  the value of T_CONTACTO.ID_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdDireccion() {
		return idDireccion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_CONTACTO.ID_DIRECCION
	 * @param idDireccion  the value for T_CONTACTO.ID_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdDireccion(String idDireccion) {
		this.idDireccion = idDireccion;
	}
}