package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class TDireccion {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.ID_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idDireccion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.CALLE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String calle;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.NUMERO_EXTERIOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String numeroExterior;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.NUMERO_INTERIOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String numeroInterior;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.REFERERNCIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String refererncia;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.REGION_FRONTERIZA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String regionFronteriza;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.COLONIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String colonia;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.LOCALIDAD
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String localidad;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.MUNICIPIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String municipio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.CODIGO_POSTAL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String codigoPostal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.ID_TIPO_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idTipoDireccion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.ID_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idCompania;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idEmisor;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.ID_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idCliente;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.ESTADO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String estado;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_DIRECCION.PAIS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String pais;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.ID_DIRECCION
	 * @return  the value of T_DIRECCION.ID_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdDireccion() {
		return idDireccion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.ID_DIRECCION
	 * @param idDireccion  the value for T_DIRECCION.ID_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdDireccion(String idDireccion) {
		this.idDireccion = idDireccion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.CALLE
	 * @return  the value of T_DIRECCION.CALLE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getCalle() {
		return calle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.CALLE
	 * @param calle  the value for T_DIRECCION.CALLE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setCalle(String calle) {
		this.calle = calle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.NUMERO_EXTERIOR
	 * @return  the value of T_DIRECCION.NUMERO_EXTERIOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNumeroExterior() {
		return numeroExterior;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.NUMERO_EXTERIOR
	 * @param numeroExterior  the value for T_DIRECCION.NUMERO_EXTERIOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.NUMERO_INTERIOR
	 * @return  the value of T_DIRECCION.NUMERO_INTERIOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getNumeroInterior() {
		return numeroInterior;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.NUMERO_INTERIOR
	 * @param numeroInterior  the value for T_DIRECCION.NUMERO_INTERIOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.REFERERNCIA
	 * @return  the value of T_DIRECCION.REFERERNCIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getRefererncia() {
		return refererncia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.REFERERNCIA
	 * @param refererncia  the value for T_DIRECCION.REFERERNCIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setRefererncia(String refererncia) {
		this.refererncia = refererncia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.REGION_FRONTERIZA
	 * @return  the value of T_DIRECCION.REGION_FRONTERIZA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getRegionFronteriza() {
		return regionFronteriza;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.REGION_FRONTERIZA
	 * @param regionFronteriza  the value for T_DIRECCION.REGION_FRONTERIZA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setRegionFronteriza(String regionFronteriza) {
		this.regionFronteriza = regionFronteriza;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.COLONIA
	 * @return  the value of T_DIRECCION.COLONIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getColonia() {
		return colonia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.COLONIA
	 * @param colonia  the value for T_DIRECCION.COLONIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.LOCALIDAD
	 * @return  the value of T_DIRECCION.LOCALIDAD
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getLocalidad() {
		return localidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.LOCALIDAD
	 * @param localidad  the value for T_DIRECCION.LOCALIDAD
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.MUNICIPIO
	 * @return  the value of T_DIRECCION.MUNICIPIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getMunicipio() {
		return municipio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.MUNICIPIO
	 * @param municipio  the value for T_DIRECCION.MUNICIPIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.CODIGO_POSTAL
	 * @return  the value of T_DIRECCION.CODIGO_POSTAL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getCodigoPostal() {
		return codigoPostal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.CODIGO_POSTAL
	 * @param codigoPostal  the value for T_DIRECCION.CODIGO_POSTAL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.ID_TIPO_DIRECCION
	 * @return  the value of T_DIRECCION.ID_TIPO_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdTipoDireccion() {
		return idTipoDireccion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.ID_TIPO_DIRECCION
	 * @param idTipoDireccion  the value for T_DIRECCION.ID_TIPO_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdTipoDireccion(String idTipoDireccion) {
		this.idTipoDireccion = idTipoDireccion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.ID_COMPANIA
	 * @return  the value of T_DIRECCION.ID_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdCompania() {
		return idCompania;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.ID_COMPANIA
	 * @param idCompania  the value for T_DIRECCION.ID_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdCompania(String idCompania) {
		this.idCompania = idCompania;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.ID_EMISOR
	 * @return  the value of T_DIRECCION.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdEmisor() {
		return idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.ID_EMISOR
	 * @param idEmisor  the value for T_DIRECCION.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdEmisor(String idEmisor) {
		this.idEmisor = idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.ID_CLIENTE
	 * @return  the value of T_DIRECCION.ID_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdCliente() {
		return idCliente;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.ID_CLIENTE
	 * @param idCliente  the value for T_DIRECCION.ID_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.ESTADO
	 * @return  the value of T_DIRECCION.ESTADO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.ESTADO
	 * @param estado  the value for T_DIRECCION.ESTADO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_DIRECCION.PAIS
	 * @return  the value of T_DIRECCION.PAIS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getPais() {
		return pais;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_DIRECCION.PAIS
	 * @param pais  the value for T_DIRECCION.PAIS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setPais(String pais) {
		this.pais = pais;
	}
}