package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TDireccionExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public TDireccionExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected TDireccionExample(TDireccionExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_DIRECCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdDireccionIsNull() {
			addCriterion("ID_DIRECCION is null");
			return this;
		}

		public Criteria andIdDireccionIsNotNull() {
			addCriterion("ID_DIRECCION is not null");
			return this;
		}

		public Criteria andIdDireccionEqualTo(String value) {
			addCriterion("ID_DIRECCION =", value, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionNotEqualTo(String value) {
			addCriterion("ID_DIRECCION <>", value, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionGreaterThan(String value) {
			addCriterion("ID_DIRECCION >", value, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionGreaterThanOrEqualTo(String value) {
			addCriterion("ID_DIRECCION >=", value, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionLessThan(String value) {
			addCriterion("ID_DIRECCION <", value, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionLessThanOrEqualTo(String value) {
			addCriterion("ID_DIRECCION <=", value, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionLike(String value) {
			addCriterion("ID_DIRECCION like", value, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionNotLike(String value) {
			addCriterion("ID_DIRECCION not like", value, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionIn(List values) {
			addCriterion("ID_DIRECCION in", values, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionNotIn(List values) {
			addCriterion("ID_DIRECCION not in", values, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionBetween(String value1, String value2) {
			addCriterion("ID_DIRECCION between", value1, value2, "idDireccion");
			return this;
		}

		public Criteria andIdDireccionNotBetween(String value1, String value2) {
			addCriterion("ID_DIRECCION not between", value1, value2,
					"idDireccion");
			return this;
		}

		public Criteria andCalleIsNull() {
			addCriterion("CALLE is null");
			return this;
		}

		public Criteria andCalleIsNotNull() {
			addCriterion("CALLE is not null");
			return this;
		}

		public Criteria andCalleEqualTo(String value) {
			addCriterion("CALLE =", value, "calle");
			return this;
		}

		public Criteria andCalleNotEqualTo(String value) {
			addCriterion("CALLE <>", value, "calle");
			return this;
		}

		public Criteria andCalleGreaterThan(String value) {
			addCriterion("CALLE >", value, "calle");
			return this;
		}

		public Criteria andCalleGreaterThanOrEqualTo(String value) {
			addCriterion("CALLE >=", value, "calle");
			return this;
		}

		public Criteria andCalleLessThan(String value) {
			addCriterion("CALLE <", value, "calle");
			return this;
		}

		public Criteria andCalleLessThanOrEqualTo(String value) {
			addCriterion("CALLE <=", value, "calle");
			return this;
		}

		public Criteria andCalleLike(String value) {
			addCriterion("CALLE like", value, "calle");
			return this;
		}

		public Criteria andCalleNotLike(String value) {
			addCriterion("CALLE not like", value, "calle");
			return this;
		}

		public Criteria andCalleIn(List values) {
			addCriterion("CALLE in", values, "calle");
			return this;
		}

		public Criteria andCalleNotIn(List values) {
			addCriterion("CALLE not in", values, "calle");
			return this;
		}

		public Criteria andCalleBetween(String value1, String value2) {
			addCriterion("CALLE between", value1, value2, "calle");
			return this;
		}

		public Criteria andCalleNotBetween(String value1, String value2) {
			addCriterion("CALLE not between", value1, value2, "calle");
			return this;
		}

		public Criteria andNumeroExteriorIsNull() {
			addCriterion("NUMERO_EXTERIOR is null");
			return this;
		}

		public Criteria andNumeroExteriorIsNotNull() {
			addCriterion("NUMERO_EXTERIOR is not null");
			return this;
		}

		public Criteria andNumeroExteriorEqualTo(String value) {
			addCriterion("NUMERO_EXTERIOR =", value, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorNotEqualTo(String value) {
			addCriterion("NUMERO_EXTERIOR <>", value, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorGreaterThan(String value) {
			addCriterion("NUMERO_EXTERIOR >", value, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorGreaterThanOrEqualTo(String value) {
			addCriterion("NUMERO_EXTERIOR >=", value, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorLessThan(String value) {
			addCriterion("NUMERO_EXTERIOR <", value, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorLessThanOrEqualTo(String value) {
			addCriterion("NUMERO_EXTERIOR <=", value, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorLike(String value) {
			addCriterion("NUMERO_EXTERIOR like", value, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorNotLike(String value) {
			addCriterion("NUMERO_EXTERIOR not like", value, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorIn(List values) {
			addCriterion("NUMERO_EXTERIOR in", values, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorNotIn(List values) {
			addCriterion("NUMERO_EXTERIOR not in", values, "numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorBetween(String value1, String value2) {
			addCriterion("NUMERO_EXTERIOR between", value1, value2,
					"numeroExterior");
			return this;
		}

		public Criteria andNumeroExteriorNotBetween(String value1, String value2) {
			addCriterion("NUMERO_EXTERIOR not between", value1, value2,
					"numeroExterior");
			return this;
		}

		public Criteria andNumeroInteriorIsNull() {
			addCriterion("NUMERO_INTERIOR is null");
			return this;
		}

		public Criteria andNumeroInteriorIsNotNull() {
			addCriterion("NUMERO_INTERIOR is not null");
			return this;
		}

		public Criteria andNumeroInteriorEqualTo(String value) {
			addCriterion("NUMERO_INTERIOR =", value, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorNotEqualTo(String value) {
			addCriterion("NUMERO_INTERIOR <>", value, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorGreaterThan(String value) {
			addCriterion("NUMERO_INTERIOR >", value, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorGreaterThanOrEqualTo(String value) {
			addCriterion("NUMERO_INTERIOR >=", value, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorLessThan(String value) {
			addCriterion("NUMERO_INTERIOR <", value, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorLessThanOrEqualTo(String value) {
			addCriterion("NUMERO_INTERIOR <=", value, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorLike(String value) {
			addCriterion("NUMERO_INTERIOR like", value, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorNotLike(String value) {
			addCriterion("NUMERO_INTERIOR not like", value, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorIn(List values) {
			addCriterion("NUMERO_INTERIOR in", values, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorNotIn(List values) {
			addCriterion("NUMERO_INTERIOR not in", values, "numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorBetween(String value1, String value2) {
			addCriterion("NUMERO_INTERIOR between", value1, value2,
					"numeroInterior");
			return this;
		}

		public Criteria andNumeroInteriorNotBetween(String value1, String value2) {
			addCriterion("NUMERO_INTERIOR not between", value1, value2,
					"numeroInterior");
			return this;
		}

		public Criteria andReferernciaIsNull() {
			addCriterion("REFERERNCIA is null");
			return this;
		}

		public Criteria andReferernciaIsNotNull() {
			addCriterion("REFERERNCIA is not null");
			return this;
		}

		public Criteria andReferernciaEqualTo(String value) {
			addCriterion("REFERERNCIA =", value, "refererncia");
			return this;
		}

		public Criteria andReferernciaNotEqualTo(String value) {
			addCriterion("REFERERNCIA <>", value, "refererncia");
			return this;
		}

		public Criteria andReferernciaGreaterThan(String value) {
			addCriterion("REFERERNCIA >", value, "refererncia");
			return this;
		}

		public Criteria andReferernciaGreaterThanOrEqualTo(String value) {
			addCriterion("REFERERNCIA >=", value, "refererncia");
			return this;
		}

		public Criteria andReferernciaLessThan(String value) {
			addCriterion("REFERERNCIA <", value, "refererncia");
			return this;
		}

		public Criteria andReferernciaLessThanOrEqualTo(String value) {
			addCriterion("REFERERNCIA <=", value, "refererncia");
			return this;
		}

		public Criteria andReferernciaLike(String value) {
			addCriterion("REFERERNCIA like", value, "refererncia");
			return this;
		}

		public Criteria andReferernciaNotLike(String value) {
			addCriterion("REFERERNCIA not like", value, "refererncia");
			return this;
		}

		public Criteria andReferernciaIn(List values) {
			addCriterion("REFERERNCIA in", values, "refererncia");
			return this;
		}

		public Criteria andReferernciaNotIn(List values) {
			addCriterion("REFERERNCIA not in", values, "refererncia");
			return this;
		}

		public Criteria andReferernciaBetween(String value1, String value2) {
			addCriterion("REFERERNCIA between", value1, value2, "refererncia");
			return this;
		}

		public Criteria andReferernciaNotBetween(String value1, String value2) {
			addCriterion("REFERERNCIA not between", value1, value2,
					"refererncia");
			return this;
		}

		public Criteria andRegionFronterizaIsNull() {
			addCriterion("REGION_FRONTERIZA is null");
			return this;
		}

		public Criteria andRegionFronterizaIsNotNull() {
			addCriterion("REGION_FRONTERIZA is not null");
			return this;
		}

		public Criteria andRegionFronterizaEqualTo(String value) {
			addCriterion("REGION_FRONTERIZA =", value, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaNotEqualTo(String value) {
			addCriterion("REGION_FRONTERIZA <>", value, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaGreaterThan(String value) {
			addCriterion("REGION_FRONTERIZA >", value, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaGreaterThanOrEqualTo(String value) {
			addCriterion("REGION_FRONTERIZA >=", value, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaLessThan(String value) {
			addCriterion("REGION_FRONTERIZA <", value, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaLessThanOrEqualTo(String value) {
			addCriterion("REGION_FRONTERIZA <=", value, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaLike(String value) {
			addCriterion("REGION_FRONTERIZA like", value, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaNotLike(String value) {
			addCriterion("REGION_FRONTERIZA not like", value,
					"regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaIn(List values) {
			addCriterion("REGION_FRONTERIZA in", values, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaNotIn(List values) {
			addCriterion("REGION_FRONTERIZA not in", values, "regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaBetween(String value1, String value2) {
			addCriterion("REGION_FRONTERIZA between", value1, value2,
					"regionFronteriza");
			return this;
		}

		public Criteria andRegionFronterizaNotBetween(String value1,
				String value2) {
			addCriterion("REGION_FRONTERIZA not between", value1, value2,
					"regionFronteriza");
			return this;
		}

		public Criteria andColoniaIsNull() {
			addCriterion("COLONIA is null");
			return this;
		}

		public Criteria andColoniaIsNotNull() {
			addCriterion("COLONIA is not null");
			return this;
		}

		public Criteria andColoniaEqualTo(String value) {
			addCriterion("COLONIA =", value, "colonia");
			return this;
		}

		public Criteria andColoniaNotEqualTo(String value) {
			addCriterion("COLONIA <>", value, "colonia");
			return this;
		}

		public Criteria andColoniaGreaterThan(String value) {
			addCriterion("COLONIA >", value, "colonia");
			return this;
		}

		public Criteria andColoniaGreaterThanOrEqualTo(String value) {
			addCriterion("COLONIA >=", value, "colonia");
			return this;
		}

		public Criteria andColoniaLessThan(String value) {
			addCriterion("COLONIA <", value, "colonia");
			return this;
		}

		public Criteria andColoniaLessThanOrEqualTo(String value) {
			addCriterion("COLONIA <=", value, "colonia");
			return this;
		}

		public Criteria andColoniaLike(String value) {
			addCriterion("COLONIA like", value, "colonia");
			return this;
		}

		public Criteria andColoniaNotLike(String value) {
			addCriterion("COLONIA not like", value, "colonia");
			return this;
		}

		public Criteria andColoniaIn(List values) {
			addCriterion("COLONIA in", values, "colonia");
			return this;
		}

		public Criteria andColoniaNotIn(List values) {
			addCriterion("COLONIA not in", values, "colonia");
			return this;
		}

		public Criteria andColoniaBetween(String value1, String value2) {
			addCriterion("COLONIA between", value1, value2, "colonia");
			return this;
		}

		public Criteria andColoniaNotBetween(String value1, String value2) {
			addCriterion("COLONIA not between", value1, value2, "colonia");
			return this;
		}

		public Criteria andLocalidadIsNull() {
			addCriterion("LOCALIDAD is null");
			return this;
		}

		public Criteria andLocalidadIsNotNull() {
			addCriterion("LOCALIDAD is not null");
			return this;
		}

		public Criteria andLocalidadEqualTo(String value) {
			addCriterion("LOCALIDAD =", value, "localidad");
			return this;
		}

		public Criteria andLocalidadNotEqualTo(String value) {
			addCriterion("LOCALIDAD <>", value, "localidad");
			return this;
		}

		public Criteria andLocalidadGreaterThan(String value) {
			addCriterion("LOCALIDAD >", value, "localidad");
			return this;
		}

		public Criteria andLocalidadGreaterThanOrEqualTo(String value) {
			addCriterion("LOCALIDAD >=", value, "localidad");
			return this;
		}

		public Criteria andLocalidadLessThan(String value) {
			addCriterion("LOCALIDAD <", value, "localidad");
			return this;
		}

		public Criteria andLocalidadLessThanOrEqualTo(String value) {
			addCriterion("LOCALIDAD <=", value, "localidad");
			return this;
		}

		public Criteria andLocalidadLike(String value) {
			addCriterion("LOCALIDAD like", value, "localidad");
			return this;
		}

		public Criteria andLocalidadNotLike(String value) {
			addCriterion("LOCALIDAD not like", value, "localidad");
			return this;
		}

		public Criteria andLocalidadIn(List values) {
			addCriterion("LOCALIDAD in", values, "localidad");
			return this;
		}

		public Criteria andLocalidadNotIn(List values) {
			addCriterion("LOCALIDAD not in", values, "localidad");
			return this;
		}

		public Criteria andLocalidadBetween(String value1, String value2) {
			addCriterion("LOCALIDAD between", value1, value2, "localidad");
			return this;
		}

		public Criteria andLocalidadNotBetween(String value1, String value2) {
			addCriterion("LOCALIDAD not between", value1, value2, "localidad");
			return this;
		}

		public Criteria andMunicipioIsNull() {
			addCriterion("MUNICIPIO is null");
			return this;
		}

		public Criteria andMunicipioIsNotNull() {
			addCriterion("MUNICIPIO is not null");
			return this;
		}

		public Criteria andMunicipioEqualTo(String value) {
			addCriterion("MUNICIPIO =", value, "municipio");
			return this;
		}

		public Criteria andMunicipioNotEqualTo(String value) {
			addCriterion("MUNICIPIO <>", value, "municipio");
			return this;
		}

		public Criteria andMunicipioGreaterThan(String value) {
			addCriterion("MUNICIPIO >", value, "municipio");
			return this;
		}

		public Criteria andMunicipioGreaterThanOrEqualTo(String value) {
			addCriterion("MUNICIPIO >=", value, "municipio");
			return this;
		}

		public Criteria andMunicipioLessThan(String value) {
			addCriterion("MUNICIPIO <", value, "municipio");
			return this;
		}

		public Criteria andMunicipioLessThanOrEqualTo(String value) {
			addCriterion("MUNICIPIO <=", value, "municipio");
			return this;
		}

		public Criteria andMunicipioLike(String value) {
			addCriterion("MUNICIPIO like", value, "municipio");
			return this;
		}

		public Criteria andMunicipioNotLike(String value) {
			addCriterion("MUNICIPIO not like", value, "municipio");
			return this;
		}

		public Criteria andMunicipioIn(List values) {
			addCriterion("MUNICIPIO in", values, "municipio");
			return this;
		}

		public Criteria andMunicipioNotIn(List values) {
			addCriterion("MUNICIPIO not in", values, "municipio");
			return this;
		}

		public Criteria andMunicipioBetween(String value1, String value2) {
			addCriterion("MUNICIPIO between", value1, value2, "municipio");
			return this;
		}

		public Criteria andMunicipioNotBetween(String value1, String value2) {
			addCriterion("MUNICIPIO not between", value1, value2, "municipio");
			return this;
		}

		public Criteria andCodigoPostalIsNull() {
			addCriterion("CODIGO_POSTAL is null");
			return this;
		}

		public Criteria andCodigoPostalIsNotNull() {
			addCriterion("CODIGO_POSTAL is not null");
			return this;
		}

		public Criteria andCodigoPostalEqualTo(String value) {
			addCriterion("CODIGO_POSTAL =", value, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalNotEqualTo(String value) {
			addCriterion("CODIGO_POSTAL <>", value, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalGreaterThan(String value) {
			addCriterion("CODIGO_POSTAL >", value, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalGreaterThanOrEqualTo(String value) {
			addCriterion("CODIGO_POSTAL >=", value, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalLessThan(String value) {
			addCriterion("CODIGO_POSTAL <", value, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalLessThanOrEqualTo(String value) {
			addCriterion("CODIGO_POSTAL <=", value, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalLike(String value) {
			addCriterion("CODIGO_POSTAL like", value, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalNotLike(String value) {
			addCriterion("CODIGO_POSTAL not like", value, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalIn(List values) {
			addCriterion("CODIGO_POSTAL in", values, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalNotIn(List values) {
			addCriterion("CODIGO_POSTAL not in", values, "codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalBetween(String value1, String value2) {
			addCriterion("CODIGO_POSTAL between", value1, value2,
					"codigoPostal");
			return this;
		}

		public Criteria andCodigoPostalNotBetween(String value1, String value2) {
			addCriterion("CODIGO_POSTAL not between", value1, value2,
					"codigoPostal");
			return this;
		}

		public Criteria andIdTipoDireccionIsNull() {
			addCriterion("ID_TIPO_DIRECCION is null");
			return this;
		}

		public Criteria andIdTipoDireccionIsNotNull() {
			addCriterion("ID_TIPO_DIRECCION is not null");
			return this;
		}

		public Criteria andIdTipoDireccionEqualTo(String value) {
			addCriterion("ID_TIPO_DIRECCION =", value, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionNotEqualTo(String value) {
			addCriterion("ID_TIPO_DIRECCION <>", value, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionGreaterThan(String value) {
			addCriterion("ID_TIPO_DIRECCION >", value, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionGreaterThanOrEqualTo(String value) {
			addCriterion("ID_TIPO_DIRECCION >=", value, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionLessThan(String value) {
			addCriterion("ID_TIPO_DIRECCION <", value, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionLessThanOrEqualTo(String value) {
			addCriterion("ID_TIPO_DIRECCION <=", value, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionLike(String value) {
			addCriterion("ID_TIPO_DIRECCION like", value, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionNotLike(String value) {
			addCriterion("ID_TIPO_DIRECCION not like", value, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionIn(List values) {
			addCriterion("ID_TIPO_DIRECCION in", values, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionNotIn(List values) {
			addCriterion("ID_TIPO_DIRECCION not in", values, "idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionBetween(String value1, String value2) {
			addCriterion("ID_TIPO_DIRECCION between", value1, value2,
					"idTipoDireccion");
			return this;
		}

		public Criteria andIdTipoDireccionNotBetween(String value1,
				String value2) {
			addCriterion("ID_TIPO_DIRECCION not between", value1, value2,
					"idTipoDireccion");
			return this;
		}

		public Criteria andIdCompaniaIsNull() {
			addCriterion("ID_COMPANIA is null");
			return this;
		}

		public Criteria andIdCompaniaIsNotNull() {
			addCriterion("ID_COMPANIA is not null");
			return this;
		}

		public Criteria andIdCompaniaEqualTo(String value) {
			addCriterion("ID_COMPANIA =", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaNotEqualTo(String value) {
			addCriterion("ID_COMPANIA <>", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaGreaterThan(String value) {
			addCriterion("ID_COMPANIA >", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaGreaterThanOrEqualTo(String value) {
			addCriterion("ID_COMPANIA >=", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaLessThan(String value) {
			addCriterion("ID_COMPANIA <", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaLessThanOrEqualTo(String value) {
			addCriterion("ID_COMPANIA <=", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaLike(String value) {
			addCriterion("ID_COMPANIA like", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaNotLike(String value) {
			addCriterion("ID_COMPANIA not like", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaIn(List values) {
			addCriterion("ID_COMPANIA in", values, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaNotIn(List values) {
			addCriterion("ID_COMPANIA not in", values, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaBetween(String value1, String value2) {
			addCriterion("ID_COMPANIA between", value1, value2, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaNotBetween(String value1, String value2) {
			addCriterion("ID_COMPANIA not between", value1, value2,
					"idCompania");
			return this;
		}

		public Criteria andIdEmisorIsNull() {
			addCriterion("ID_EMISOR is null");
			return this;
		}

		public Criteria andIdEmisorIsNotNull() {
			addCriterion("ID_EMISOR is not null");
			return this;
		}

		public Criteria andIdEmisorEqualTo(String value) {
			addCriterion("ID_EMISOR =", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotEqualTo(String value) {
			addCriterion("ID_EMISOR <>", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThan(String value) {
			addCriterion("ID_EMISOR >", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR >=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThan(String value) {
			addCriterion("ID_EMISOR <", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR <=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLike(String value) {
			addCriterion("ID_EMISOR like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotLike(String value) {
			addCriterion("ID_EMISOR not like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorIn(List values) {
			addCriterion("ID_EMISOR in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotIn(List values) {
			addCriterion("ID_EMISOR not in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorBetween(String value1, String value2) {
			addCriterion("ID_EMISOR between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotBetween(String value1, String value2) {
			addCriterion("ID_EMISOR not between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andIdClienteIsNull() {
			addCriterion("ID_CLIENTE is null");
			return this;
		}

		public Criteria andIdClienteIsNotNull() {
			addCriterion("ID_CLIENTE is not null");
			return this;
		}

		public Criteria andIdClienteEqualTo(String value) {
			addCriterion("ID_CLIENTE =", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotEqualTo(String value) {
			addCriterion("ID_CLIENTE <>", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteGreaterThan(String value) {
			addCriterion("ID_CLIENTE >", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteGreaterThanOrEqualTo(String value) {
			addCriterion("ID_CLIENTE >=", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLessThan(String value) {
			addCriterion("ID_CLIENTE <", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLessThanOrEqualTo(String value) {
			addCriterion("ID_CLIENTE <=", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteLike(String value) {
			addCriterion("ID_CLIENTE like", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotLike(String value) {
			addCriterion("ID_CLIENTE not like", value, "idCliente");
			return this;
		}

		public Criteria andIdClienteIn(List values) {
			addCriterion("ID_CLIENTE in", values, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotIn(List values) {
			addCriterion("ID_CLIENTE not in", values, "idCliente");
			return this;
		}

		public Criteria andIdClienteBetween(String value1, String value2) {
			addCriterion("ID_CLIENTE between", value1, value2, "idCliente");
			return this;
		}

		public Criteria andIdClienteNotBetween(String value1, String value2) {
			addCriterion("ID_CLIENTE not between", value1, value2, "idCliente");
			return this;
		}

		public Criteria andEstadoIsNull() {
			addCriterion("ESTADO is null");
			return this;
		}

		public Criteria andEstadoIsNotNull() {
			addCriterion("ESTADO is not null");
			return this;
		}

		public Criteria andEstadoEqualTo(String value) {
			addCriterion("ESTADO =", value, "estado");
			return this;
		}

		public Criteria andEstadoNotEqualTo(String value) {
			addCriterion("ESTADO <>", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThan(String value) {
			addCriterion("ESTADO >", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThanOrEqualTo(String value) {
			addCriterion("ESTADO >=", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThan(String value) {
			addCriterion("ESTADO <", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThanOrEqualTo(String value) {
			addCriterion("ESTADO <=", value, "estado");
			return this;
		}

		public Criteria andEstadoLike(String value) {
			addCriterion("ESTADO like", value, "estado");
			return this;
		}

		public Criteria andEstadoNotLike(String value) {
			addCriterion("ESTADO not like", value, "estado");
			return this;
		}

		public Criteria andEstadoIn(List values) {
			addCriterion("ESTADO in", values, "estado");
			return this;
		}

		public Criteria andEstadoNotIn(List values) {
			addCriterion("ESTADO not in", values, "estado");
			return this;
		}

		public Criteria andEstadoBetween(String value1, String value2) {
			addCriterion("ESTADO between", value1, value2, "estado");
			return this;
		}

		public Criteria andEstadoNotBetween(String value1, String value2) {
			addCriterion("ESTADO not between", value1, value2, "estado");
			return this;
		}

		public Criteria andPaisIsNull() {
			addCriterion("PAIS is null");
			return this;
		}

		public Criteria andPaisIsNotNull() {
			addCriterion("PAIS is not null");
			return this;
		}

		public Criteria andPaisEqualTo(String value) {
			addCriterion("PAIS =", value, "pais");
			return this;
		}

		public Criteria andPaisNotEqualTo(String value) {
			addCriterion("PAIS <>", value, "pais");
			return this;
		}

		public Criteria andPaisGreaterThan(String value) {
			addCriterion("PAIS >", value, "pais");
			return this;
		}

		public Criteria andPaisGreaterThanOrEqualTo(String value) {
			addCriterion("PAIS >=", value, "pais");
			return this;
		}

		public Criteria andPaisLessThan(String value) {
			addCriterion("PAIS <", value, "pais");
			return this;
		}

		public Criteria andPaisLessThanOrEqualTo(String value) {
			addCriterion("PAIS <=", value, "pais");
			return this;
		}

		public Criteria andPaisLike(String value) {
			addCriterion("PAIS like", value, "pais");
			return this;
		}

		public Criteria andPaisNotLike(String value) {
			addCriterion("PAIS not like", value, "pais");
			return this;
		}

		public Criteria andPaisIn(List values) {
			addCriterion("PAIS in", values, "pais");
			return this;
		}

		public Criteria andPaisNotIn(List values) {
			addCriterion("PAIS not in", values, "pais");
			return this;
		}

		public Criteria andPaisBetween(String value1, String value2) {
			addCriterion("PAIS between", value1, value2, "pais");
			return this;
		}

		public Criteria andPaisNotBetween(String value1, String value2) {
			addCriterion("PAIS not between", value1, value2, "pais");
			return this;
		}
	}
}