package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TEmisorExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public TEmisorExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	protected TEmisorExample(TEmisorExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdEmisorIsNull() {
			addCriterion("ID_EMISOR is null");
			return this;
		}

		public Criteria andIdEmisorIsNotNull() {
			addCriterion("ID_EMISOR is not null");
			return this;
		}

		public Criteria andIdEmisorEqualTo(String value) {
			addCriterion("ID_EMISOR =", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotEqualTo(String value) {
			addCriterion("ID_EMISOR <>", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThan(String value) {
			addCriterion("ID_EMISOR >", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR >=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThan(String value) {
			addCriterion("ID_EMISOR <", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR <=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLike(String value) {
			addCriterion("ID_EMISOR like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotLike(String value) {
			addCriterion("ID_EMISOR not like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorIn(List values) {
			addCriterion("ID_EMISOR in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotIn(List values) {
			addCriterion("ID_EMISOR not in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorBetween(String value1, String value2) {
			addCriterion("ID_EMISOR between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotBetween(String value1, String value2) {
			addCriterion("ID_EMISOR not between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andTEmisorPIsNull() {
			addCriterion("T_EMISOR_P is null");
			return this;
		}

		public Criteria andTEmisorPIsNotNull() {
			addCriterion("T_EMISOR_P is not null");
			return this;
		}

		public Criteria andTEmisorPEqualTo(String value) {
			addCriterion("T_EMISOR_P =", value, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPNotEqualTo(String value) {
			addCriterion("T_EMISOR_P <>", value, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPGreaterThan(String value) {
			addCriterion("T_EMISOR_P >", value, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPGreaterThanOrEqualTo(String value) {
			addCriterion("T_EMISOR_P >=", value, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPLessThan(String value) {
			addCriterion("T_EMISOR_P <", value, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPLessThanOrEqualTo(String value) {
			addCriterion("T_EMISOR_P <=", value, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPLike(String value) {
			addCriterion("T_EMISOR_P like", value, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPNotLike(String value) {
			addCriterion("T_EMISOR_P not like", value, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPIn(List values) {
			addCriterion("T_EMISOR_P in", values, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPNotIn(List values) {
			addCriterion("T_EMISOR_P not in", values, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPBetween(String value1, String value2) {
			addCriterion("T_EMISOR_P between", value1, value2, "tEmisorP");
			return this;
		}

		public Criteria andTEmisorPNotBetween(String value1, String value2) {
			addCriterion("T_EMISOR_P not between", value1, value2, "tEmisorP");
			return this;
		}

		public Criteria andRfcIsNull() {
			addCriterion("RFC is null");
			return this;
		}

		public Criteria andRfcIsNotNull() {
			addCriterion("RFC is not null");
			return this;
		}

		public Criteria andRfcEqualTo(String value) {
			addCriterion("RFC =", value, "rfc");
			return this;
		}

		public Criteria andRfcNotEqualTo(String value) {
			addCriterion("RFC <>", value, "rfc");
			return this;
		}

		public Criteria andRfcGreaterThan(String value) {
			addCriterion("RFC >", value, "rfc");
			return this;
		}

		public Criteria andRfcGreaterThanOrEqualTo(String value) {
			addCriterion("RFC >=", value, "rfc");
			return this;
		}

		public Criteria andRfcLessThan(String value) {
			addCriterion("RFC <", value, "rfc");
			return this;
		}

		public Criteria andRfcLessThanOrEqualTo(String value) {
			addCriterion("RFC <=", value, "rfc");
			return this;
		}

		public Criteria andRfcLike(String value) {
			addCriterion("RFC like", value, "rfc");
			return this;
		}

		public Criteria andRfcNotLike(String value) {
			addCriterion("RFC not like", value, "rfc");
			return this;
		}

		public Criteria andRfcIn(List values) {
			addCriterion("RFC in", values, "rfc");
			return this;
		}

		public Criteria andRfcNotIn(List values) {
			addCriterion("RFC not in", values, "rfc");
			return this;
		}

		public Criteria andRfcBetween(String value1, String value2) {
			addCriterion("RFC between", value1, value2, "rfc");
			return this;
		}

		public Criteria andRfcNotBetween(String value1, String value2) {
			addCriterion("RFC not between", value1, value2, "rfc");
			return this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("NOMBRE is null");
			return this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("NOMBRE is not null");
			return this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("NOMBRE =", value, "nombre");
			return this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("NOMBRE <>", value, "nombre");
			return this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("NOMBRE >", value, "nombre");
			return this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE >=", value, "nombre");
			return this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("NOMBRE <", value, "nombre");
			return this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE <=", value, "nombre");
			return this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("NOMBRE like", value, "nombre");
			return this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("NOMBRE not like", value, "nombre");
			return this;
		}

		public Criteria andNombreIn(List values) {
			addCriterion("NOMBRE in", values, "nombre");
			return this;
		}

		public Criteria andNombreNotIn(List values) {
			addCriterion("NOMBRE not in", values, "nombre");
			return this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("NOMBRE between", value1, value2, "nombre");
			return this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("NOMBRE not between", value1, value2, "nombre");
			return this;
		}

		public Criteria andIdTipoPersonaIsNull() {
			addCriterion("ID_TIPO_PERSONA is null");
			return this;
		}

		public Criteria andIdTipoPersonaIsNotNull() {
			addCriterion("ID_TIPO_PERSONA is not null");
			return this;
		}

		public Criteria andIdTipoPersonaEqualTo(String value) {
			addCriterion("ID_TIPO_PERSONA =", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaNotEqualTo(String value) {
			addCriterion("ID_TIPO_PERSONA <>", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaGreaterThan(String value) {
			addCriterion("ID_TIPO_PERSONA >", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaGreaterThanOrEqualTo(String value) {
			addCriterion("ID_TIPO_PERSONA >=", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaLessThan(String value) {
			addCriterion("ID_TIPO_PERSONA <", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaLessThanOrEqualTo(String value) {
			addCriterion("ID_TIPO_PERSONA <=", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaLike(String value) {
			addCriterion("ID_TIPO_PERSONA like", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaNotLike(String value) {
			addCriterion("ID_TIPO_PERSONA not like", value, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaIn(List values) {
			addCriterion("ID_TIPO_PERSONA in", values, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaNotIn(List values) {
			addCriterion("ID_TIPO_PERSONA not in", values, "idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaBetween(String value1, String value2) {
			addCriterion("ID_TIPO_PERSONA between", value1, value2,
					"idTipoPersona");
			return this;
		}

		public Criteria andIdTipoPersonaNotBetween(String value1, String value2) {
			addCriterion("ID_TIPO_PERSONA not between", value1, value2,
					"idTipoPersona");
			return this;
		}

		public Criteria andIdCompaniaIsNull() {
			addCriterion("ID_COMPANIA is null");
			return this;
		}

		public Criteria andIdCompaniaIsNotNull() {
			addCriterion("ID_COMPANIA is not null");
			return this;
		}

		public Criteria andIdCompaniaEqualTo(String value) {
			addCriterion("ID_COMPANIA =", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaNotEqualTo(String value) {
			addCriterion("ID_COMPANIA <>", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaGreaterThan(String value) {
			addCriterion("ID_COMPANIA >", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaGreaterThanOrEqualTo(String value) {
			addCriterion("ID_COMPANIA >=", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaLessThan(String value) {
			addCriterion("ID_COMPANIA <", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaLessThanOrEqualTo(String value) {
			addCriterion("ID_COMPANIA <=", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaLike(String value) {
			addCriterion("ID_COMPANIA like", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaNotLike(String value) {
			addCriterion("ID_COMPANIA not like", value, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaIn(List values) {
			addCriterion("ID_COMPANIA in", values, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaNotIn(List values) {
			addCriterion("ID_COMPANIA not in", values, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaBetween(String value1, String value2) {
			addCriterion("ID_COMPANIA between", value1, value2, "idCompania");
			return this;
		}

		public Criteria andIdCompaniaNotBetween(String value1, String value2) {
			addCriterion("ID_COMPANIA not between", value1, value2,
					"idCompania");
			return this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return this;
		}

		public Criteria andEmailIn(List values) {
			addCriterion("EMAIL in", values, "email");
			return this;
		}

		public Criteria andEmailNotIn(List values) {
			addCriterion("EMAIL not in", values, "email");
			return this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return this;
		}

		public Criteria andEmailPwdIsNull() {
			addCriterion("EMAIL_PWD is null");
			return this;
		}

		public Criteria andEmailPwdIsNotNull() {
			addCriterion("EMAIL_PWD is not null");
			return this;
		}

		public Criteria andEmailPwdEqualTo(String value) {
			addCriterion("EMAIL_PWD =", value, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdNotEqualTo(String value) {
			addCriterion("EMAIL_PWD <>", value, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdGreaterThan(String value) {
			addCriterion("EMAIL_PWD >", value, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL_PWD >=", value, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdLessThan(String value) {
			addCriterion("EMAIL_PWD <", value, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdLessThanOrEqualTo(String value) {
			addCriterion("EMAIL_PWD <=", value, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdLike(String value) {
			addCriterion("EMAIL_PWD like", value, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdNotLike(String value) {
			addCriterion("EMAIL_PWD not like", value, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdIn(List values) {
			addCriterion("EMAIL_PWD in", values, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdNotIn(List values) {
			addCriterion("EMAIL_PWD not in", values, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdBetween(String value1, String value2) {
			addCriterion("EMAIL_PWD between", value1, value2, "emailPwd");
			return this;
		}

		public Criteria andEmailPwdNotBetween(String value1, String value2) {
			addCriterion("EMAIL_PWD not between", value1, value2, "emailPwd");
			return this;
		}
	}
}