package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class TEmisor {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_EMISOR.ID_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	private String idEmisor;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_EMISOR.T_EMISOR_P
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	private String tEmisorP;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_EMISOR.RFC
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	private String rfc;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_EMISOR.NOMBRE
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_EMISOR.ID_TIPO_PERSONA
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	private String idTipoPersona;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_EMISOR.ID_COMPANIA
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	private String idCompania;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_EMISOR.EMAIL
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_EMISOR.EMAIL_PWD
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	private String emailPwd;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_EMISOR.ID_EMISOR
	 * @return  the value of T_EMISOR.ID_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String getIdEmisor() {
		return idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_EMISOR.ID_EMISOR
	 * @param idEmisor  the value for T_EMISOR.ID_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void setIdEmisor(String idEmisor) {
		this.idEmisor = idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_EMISOR.T_EMISOR_P
	 * @return  the value of T_EMISOR.T_EMISOR_P
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String gettEmisorP() {
		return tEmisorP;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_EMISOR.T_EMISOR_P
	 * @param tEmisorP  the value for T_EMISOR.T_EMISOR_P
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void settEmisorP(String tEmisorP) {
		this.tEmisorP = tEmisorP;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_EMISOR.RFC
	 * @return  the value of T_EMISOR.RFC
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String getRfc() {
		return rfc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_EMISOR.RFC
	 * @param rfc  the value for T_EMISOR.RFC
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_EMISOR.NOMBRE
	 * @return  the value of T_EMISOR.NOMBRE
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_EMISOR.NOMBRE
	 * @param nombre  the value for T_EMISOR.NOMBRE
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_EMISOR.ID_TIPO_PERSONA
	 * @return  the value of T_EMISOR.ID_TIPO_PERSONA
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String getIdTipoPersona() {
		return idTipoPersona;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_EMISOR.ID_TIPO_PERSONA
	 * @param idTipoPersona  the value for T_EMISOR.ID_TIPO_PERSONA
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void setIdTipoPersona(String idTipoPersona) {
		this.idTipoPersona = idTipoPersona;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_EMISOR.ID_COMPANIA
	 * @return  the value of T_EMISOR.ID_COMPANIA
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String getIdCompania() {
		return idCompania;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_EMISOR.ID_COMPANIA
	 * @param idCompania  the value for T_EMISOR.ID_COMPANIA
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void setIdCompania(String idCompania) {
		this.idCompania = idCompania;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_EMISOR.EMAIL
	 * @return  the value of T_EMISOR.EMAIL
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_EMISOR.EMAIL
	 * @param email  the value for T_EMISOR.EMAIL
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_EMISOR.EMAIL_PWD
	 * @return  the value of T_EMISOR.EMAIL_PWD
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public String getEmailPwd() {
		return emailPwd;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_EMISOR.EMAIL_PWD
	 * @param emailPwd  the value for T_EMISOR.EMAIL_PWD
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	public void setEmailPwd(String emailPwd) {
		this.emailPwd = emailPwd;
	}
}