package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;

public class TProductoServicio {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_PRODUCTO_SERVICIO.ID_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idProductoServicio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_PRODUCTO_SERVICIO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String descripcion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_PRODUCTO_SERVICIO.PRECIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String precio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_PRODUCTO_SERVICIO.UNIDAD
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String unidad;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_PRODUCTO_SERVICIO.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private String idEmisor;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_PRODUCTO_SERVICIO.ID_PRODUCTO_SERVICIO
	 * @return  the value of T_PRODUCTO_SERVICIO.ID_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdProductoServicio() {
		return idProductoServicio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_PRODUCTO_SERVICIO.ID_PRODUCTO_SERVICIO
	 * @param idProductoServicio  the value for T_PRODUCTO_SERVICIO.ID_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdProductoServicio(String idProductoServicio) {
		this.idProductoServicio = idProductoServicio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_PRODUCTO_SERVICIO.DESCRIPCION
	 * @return  the value of T_PRODUCTO_SERVICIO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_PRODUCTO_SERVICIO.DESCRIPCION
	 * @param descripcion  the value for T_PRODUCTO_SERVICIO.DESCRIPCION
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_PRODUCTO_SERVICIO.PRECIO
	 * @return  the value of T_PRODUCTO_SERVICIO.PRECIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getPrecio() {
		return precio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_PRODUCTO_SERVICIO.PRECIO
	 * @param precio  the value for T_PRODUCTO_SERVICIO.PRECIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setPrecio(String precio) {
		this.precio = precio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_PRODUCTO_SERVICIO.UNIDAD
	 * @return  the value of T_PRODUCTO_SERVICIO.UNIDAD
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getUnidad() {
		return unidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_PRODUCTO_SERVICIO.UNIDAD
	 * @param unidad  the value for T_PRODUCTO_SERVICIO.UNIDAD
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_PRODUCTO_SERVICIO.ID_EMISOR
	 * @return  the value of T_PRODUCTO_SERVICIO.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getIdEmisor() {
		return idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_PRODUCTO_SERVICIO.ID_EMISOR
	 * @param idEmisor  the value for T_PRODUCTO_SERVICIO.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setIdEmisor(String idEmisor) {
		this.idEmisor = idEmisor;
	}
}