package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.Date;

public class TSerie {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.ID_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String idSerie;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String serie;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.FOLIO_INICIAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String folioInicial;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.FOLIO_FINAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String folioFinal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.FECHA_INICIO
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String fechaInicio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.FECHA_FIN
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String fechaFin;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String idEmisor;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.FOLIO_ACTUAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String folioActual;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.ANIO_APROBACION
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String anioAprobacion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column T_SERIE.NO_APROBACION
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private String noAprobacion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.ID_SERIE
	 * @return  the value of T_SERIE.ID_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getIdSerie() {
		return idSerie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.ID_SERIE
	 * @param idSerie  the value for T_SERIE.ID_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.SERIE
	 * @return  the value of T_SERIE.SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getSerie() {
		return serie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.SERIE
	 * @param serie  the value for T_SERIE.SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setSerie(String serie) {
		this.serie = serie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.FOLIO_INICIAL
	 * @return  the value of T_SERIE.FOLIO_INICIAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getFolioInicial() {
		return folioInicial;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.FOLIO_INICIAL
	 * @param folioInicial  the value for T_SERIE.FOLIO_INICIAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setFolioInicial(String folioInicial) {
		this.folioInicial = folioInicial;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.FOLIO_FINAL
	 * @return  the value of T_SERIE.FOLIO_FINAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getFolioFinal() {
		return folioFinal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.FOLIO_FINAL
	 * @param folioFinal  the value for T_SERIE.FOLIO_FINAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setFolioFinal(String folioFinal) {
		this.folioFinal = folioFinal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.FECHA_INICIO
	 * @return  the value of T_SERIE.FECHA_INICIO
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getFechaInicio() {
		return fechaInicio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.FECHA_INICIO
	 * @param fechaInicio  the value for T_SERIE.FECHA_INICIO
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setFechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.FECHA_FIN
	 * @return  the value of T_SERIE.FECHA_FIN
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getFechaFin() {
		return fechaFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.FECHA_FIN
	 * @param fechaFin  the value for T_SERIE.FECHA_FIN
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setFechaFin(String fechaFin) {
		this.fechaFin = fechaFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.ID_EMISOR
	 * @return  the value of T_SERIE.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getIdEmisor() {
		return idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.ID_EMISOR
	 * @param idEmisor  the value for T_SERIE.ID_EMISOR
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setIdEmisor(String idEmisor) {
		this.idEmisor = idEmisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.FOLIO_ACTUAL
	 * @return  the value of T_SERIE.FOLIO_ACTUAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getFolioActual() {
		return folioActual;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.FOLIO_ACTUAL
	 * @param folioActual  the value for T_SERIE.FOLIO_ACTUAL
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setFolioActual(String folioActual) {
		this.folioActual = folioActual;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.ANIO_APROBACION
	 * @return  the value of T_SERIE.ANIO_APROBACION
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getAnioAprobacion() {
		return anioAprobacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.ANIO_APROBACION
	 * @param anioAprobacion  the value for T_SERIE.ANIO_APROBACION
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setAnioAprobacion(String anioAprobacion) {
		this.anioAprobacion = anioAprobacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column T_SERIE.NO_APROBACION
	 * @return  the value of T_SERIE.NO_APROBACION
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getNoAprobacion() {
		return noAprobacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column T_SERIE.NO_APROBACION
	 * @param noAprobacion  the value for T_SERIE.NO_APROBACION
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setNoAprobacion(String noAprobacion) {
		this.noAprobacion = noAprobacion;
	}
}