package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TSerieExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public TSerieExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	protected TSerieExample(TSerieExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdSerieIsNull() {
			addCriterion("ID_SERIE is null");
			return this;
		}

		public Criteria andIdSerieIsNotNull() {
			addCriterion("ID_SERIE is not null");
			return this;
		}

		public Criteria andIdSerieEqualTo(String value) {
			addCriterion("ID_SERIE =", value, "idSerie");
			return this;
		}

		public Criteria andIdSerieNotEqualTo(String value) {
			addCriterion("ID_SERIE <>", value, "idSerie");
			return this;
		}

		public Criteria andIdSerieGreaterThan(String value) {
			addCriterion("ID_SERIE >", value, "idSerie");
			return this;
		}

		public Criteria andIdSerieGreaterThanOrEqualTo(String value) {
			addCriterion("ID_SERIE >=", value, "idSerie");
			return this;
		}

		public Criteria andIdSerieLessThan(String value) {
			addCriterion("ID_SERIE <", value, "idSerie");
			return this;
		}

		public Criteria andIdSerieLessThanOrEqualTo(String value) {
			addCriterion("ID_SERIE <=", value, "idSerie");
			return this;
		}

		public Criteria andIdSerieLike(String value) {
			addCriterion("ID_SERIE like", value, "idSerie");
			return this;
		}

		public Criteria andIdSerieNotLike(String value) {
			addCriterion("ID_SERIE not like", value, "idSerie");
			return this;
		}

		public Criteria andIdSerieIn(List values) {
			addCriterion("ID_SERIE in", values, "idSerie");
			return this;
		}

		public Criteria andIdSerieNotIn(List values) {
			addCriterion("ID_SERIE not in", values, "idSerie");
			return this;
		}

		public Criteria andIdSerieBetween(String value1, String value2) {
			addCriterion("ID_SERIE between", value1, value2, "idSerie");
			return this;
		}

		public Criteria andIdSerieNotBetween(String value1, String value2) {
			addCriterion("ID_SERIE not between", value1, value2, "idSerie");
			return this;
		}

		public Criteria andSerieIsNull() {
			addCriterion("SERIE is null");
			return this;
		}

		public Criteria andSerieIsNotNull() {
			addCriterion("SERIE is not null");
			return this;
		}

		public Criteria andSerieEqualTo(String value) {
			addCriterion("SERIE =", value, "serie");
			return this;
		}

		public Criteria andSerieNotEqualTo(String value) {
			addCriterion("SERIE <>", value, "serie");
			return this;
		}

		public Criteria andSerieGreaterThan(String value) {
			addCriterion("SERIE >", value, "serie");
			return this;
		}

		public Criteria andSerieGreaterThanOrEqualTo(String value) {
			addCriterion("SERIE >=", value, "serie");
			return this;
		}

		public Criteria andSerieLessThan(String value) {
			addCriterion("SERIE <", value, "serie");
			return this;
		}

		public Criteria andSerieLessThanOrEqualTo(String value) {
			addCriterion("SERIE <=", value, "serie");
			return this;
		}

		public Criteria andSerieLike(String value) {
			addCriterion("SERIE like", value, "serie");
			return this;
		}

		public Criteria andSerieNotLike(String value) {
			addCriterion("SERIE not like", value, "serie");
			return this;
		}

		public Criteria andSerieIn(List values) {
			addCriterion("SERIE in", values, "serie");
			return this;
		}

		public Criteria andSerieNotIn(List values) {
			addCriterion("SERIE not in", values, "serie");
			return this;
		}

		public Criteria andSerieBetween(String value1, String value2) {
			addCriterion("SERIE between", value1, value2, "serie");
			return this;
		}

		public Criteria andSerieNotBetween(String value1, String value2) {
			addCriterion("SERIE not between", value1, value2, "serie");
			return this;
		}

		public Criteria andFolioInicialIsNull() {
			addCriterion("FOLIO_INICIAL is null");
			return this;
		}

		public Criteria andFolioInicialIsNotNull() {
			addCriterion("FOLIO_INICIAL is not null");
			return this;
		}

		public Criteria andFolioInicialEqualTo(String value) {
			addCriterion("FOLIO_INICIAL =", value, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialNotEqualTo(String value) {
			addCriterion("FOLIO_INICIAL <>", value, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialGreaterThan(String value) {
			addCriterion("FOLIO_INICIAL >", value, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialGreaterThanOrEqualTo(String value) {
			addCriterion("FOLIO_INICIAL >=", value, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialLessThan(String value) {
			addCriterion("FOLIO_INICIAL <", value, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialLessThanOrEqualTo(String value) {
			addCriterion("FOLIO_INICIAL <=", value, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialLike(String value) {
			addCriterion("FOLIO_INICIAL like", value, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialNotLike(String value) {
			addCriterion("FOLIO_INICIAL not like", value, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialIn(List values) {
			addCriterion("FOLIO_INICIAL in", values, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialNotIn(List values) {
			addCriterion("FOLIO_INICIAL not in", values, "folioInicial");
			return this;
		}

		public Criteria andFolioInicialBetween(String value1, String value2) {
			addCriterion("FOLIO_INICIAL between", value1, value2,
					"folioInicial");
			return this;
		}

		public Criteria andFolioInicialNotBetween(String value1, String value2) {
			addCriterion("FOLIO_INICIAL not between", value1, value2,
					"folioInicial");
			return this;
		}

		public Criteria andFolioFinalIsNull() {
			addCriterion("FOLIO_FINAL is null");
			return this;
		}

		public Criteria andFolioFinalIsNotNull() {
			addCriterion("FOLIO_FINAL is not null");
			return this;
		}

		public Criteria andFolioFinalEqualTo(String value) {
			addCriterion("FOLIO_FINAL =", value, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalNotEqualTo(String value) {
			addCriterion("FOLIO_FINAL <>", value, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalGreaterThan(String value) {
			addCriterion("FOLIO_FINAL >", value, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalGreaterThanOrEqualTo(String value) {
			addCriterion("FOLIO_FINAL >=", value, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalLessThan(String value) {
			addCriterion("FOLIO_FINAL <", value, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalLessThanOrEqualTo(String value) {
			addCriterion("FOLIO_FINAL <=", value, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalLike(String value) {
			addCriterion("FOLIO_FINAL like", value, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalNotLike(String value) {
			addCriterion("FOLIO_FINAL not like", value, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalIn(List values) {
			addCriterion("FOLIO_FINAL in", values, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalNotIn(List values) {
			addCriterion("FOLIO_FINAL not in", values, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalBetween(String value1, String value2) {
			addCriterion("FOLIO_FINAL between", value1, value2, "folioFinal");
			return this;
		}

		public Criteria andFolioFinalNotBetween(String value1, String value2) {
			addCriterion("FOLIO_FINAL not between", value1, value2,
					"folioFinal");
			return this;
		}

		public Criteria andFechaInicioIsNull() {
			addCriterion("FECHA_INICIO is null");
			return this;
		}

		public Criteria andFechaInicioIsNotNull() {
			addCriterion("FECHA_INICIO is not null");
			return this;
		}

		public Criteria andFechaInicioEqualTo(String value) {
			addCriterion("FECHA_INICIO =", value, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioNotEqualTo(String value) {
			addCriterion("FECHA_INICIO <>", value, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioGreaterThan(String value) {
			addCriterion("FECHA_INICIO >", value, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioGreaterThanOrEqualTo(String value) {
			addCriterion("FECHA_INICIO >=", value, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioLessThan(String value) {
			addCriterion("FECHA_INICIO <", value, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioLessThanOrEqualTo(String value) {
			addCriterion("FECHA_INICIO <=", value, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioLike(String value) {
			addCriterion("FECHA_INICIO like", value, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioNotLike(String value) {
			addCriterion("FECHA_INICIO not like", value, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioIn(List values) {
			addCriterion("FECHA_INICIO in", values, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioNotIn(List values) {
			addCriterion("FECHA_INICIO not in", values, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioBetween(String value1, String value2) {
			addCriterion("FECHA_INICIO between", value1, value2, "fechaInicio");
			return this;
		}

		public Criteria andFechaInicioNotBetween(String value1, String value2) {
			addCriterion("FECHA_INICIO not between", value1, value2,
					"fechaInicio");
			return this;
		}

		public Criteria andFechaFinIsNull() {
			addCriterion("FECHA_FIN is null");
			return this;
		}

		public Criteria andFechaFinIsNotNull() {
			addCriterion("FECHA_FIN is not null");
			return this;
		}

		public Criteria andFechaFinEqualTo(String value) {
			addCriterion("FECHA_FIN =", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotEqualTo(String value) {
			addCriterion("FECHA_FIN <>", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinGreaterThan(String value) {
			addCriterion("FECHA_FIN >", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinGreaterThanOrEqualTo(String value) {
			addCriterion("FECHA_FIN >=", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinLessThan(String value) {
			addCriterion("FECHA_FIN <", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinLessThanOrEqualTo(String value) {
			addCriterion("FECHA_FIN <=", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinLike(String value) {
			addCriterion("FECHA_FIN like", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotLike(String value) {
			addCriterion("FECHA_FIN not like", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinIn(List values) {
			addCriterion("FECHA_FIN in", values, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotIn(List values) {
			addCriterion("FECHA_FIN not in", values, "fechaFin");
			return this;
		}

		public Criteria andFechaFinBetween(String value1, String value2) {
			addCriterion("FECHA_FIN between", value1, value2, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotBetween(String value1, String value2) {
			addCriterion("FECHA_FIN not between", value1, value2, "fechaFin");
			return this;
		}

		public Criteria andIdEmisorIsNull() {
			addCriterion("ID_EMISOR is null");
			return this;
		}

		public Criteria andIdEmisorIsNotNull() {
			addCriterion("ID_EMISOR is not null");
			return this;
		}

		public Criteria andIdEmisorEqualTo(String value) {
			addCriterion("ID_EMISOR =", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotEqualTo(String value) {
			addCriterion("ID_EMISOR <>", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThan(String value) {
			addCriterion("ID_EMISOR >", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR >=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThan(String value) {
			addCriterion("ID_EMISOR <", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR <=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLike(String value) {
			addCriterion("ID_EMISOR like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotLike(String value) {
			addCriterion("ID_EMISOR not like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorIn(List values) {
			addCriterion("ID_EMISOR in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotIn(List values) {
			addCriterion("ID_EMISOR not in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorBetween(String value1, String value2) {
			addCriterion("ID_EMISOR between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotBetween(String value1, String value2) {
			addCriterion("ID_EMISOR not between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andFolioActualIsNull() {
			addCriterion("FOLIO_ACTUAL is null");
			return this;
		}

		public Criteria andFolioActualIsNotNull() {
			addCriterion("FOLIO_ACTUAL is not null");
			return this;
		}

		public Criteria andFolioActualEqualTo(String value) {
			addCriterion("FOLIO_ACTUAL =", value, "folioActual");
			return this;
		}

		public Criteria andFolioActualNotEqualTo(String value) {
			addCriterion("FOLIO_ACTUAL <>", value, "folioActual");
			return this;
		}

		public Criteria andFolioActualGreaterThan(String value) {
			addCriterion("FOLIO_ACTUAL >", value, "folioActual");
			return this;
		}

		public Criteria andFolioActualGreaterThanOrEqualTo(String value) {
			addCriterion("FOLIO_ACTUAL >=", value, "folioActual");
			return this;
		}

		public Criteria andFolioActualLessThan(String value) {
			addCriterion("FOLIO_ACTUAL <", value, "folioActual");
			return this;
		}

		public Criteria andFolioActualLessThanOrEqualTo(String value) {
			addCriterion("FOLIO_ACTUAL <=", value, "folioActual");
			return this;
		}

		public Criteria andFolioActualLike(String value) {
			addCriterion("FOLIO_ACTUAL like", value, "folioActual");
			return this;
		}

		public Criteria andFolioActualNotLike(String value) {
			addCriterion("FOLIO_ACTUAL not like", value, "folioActual");
			return this;
		}

		public Criteria andFolioActualIn(List values) {
			addCriterion("FOLIO_ACTUAL in", values, "folioActual");
			return this;
		}

		public Criteria andFolioActualNotIn(List values) {
			addCriterion("FOLIO_ACTUAL not in", values, "folioActual");
			return this;
		}

		public Criteria andFolioActualBetween(String value1, String value2) {
			addCriterion("FOLIO_ACTUAL between", value1, value2, "folioActual");
			return this;
		}

		public Criteria andFolioActualNotBetween(String value1, String value2) {
			addCriterion("FOLIO_ACTUAL not between", value1, value2,
					"folioActual");
			return this;
		}

		public Criteria andAnioAprobacionIsNull() {
			addCriterion("ANIO_APROBACION is null");
			return this;
		}

		public Criteria andAnioAprobacionIsNotNull() {
			addCriterion("ANIO_APROBACION is not null");
			return this;
		}

		public Criteria andAnioAprobacionEqualTo(String value) {
			addCriterion("ANIO_APROBACION =", value, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionNotEqualTo(String value) {
			addCriterion("ANIO_APROBACION <>", value, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionGreaterThan(String value) {
			addCriterion("ANIO_APROBACION >", value, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionGreaterThanOrEqualTo(String value) {
			addCriterion("ANIO_APROBACION >=", value, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionLessThan(String value) {
			addCriterion("ANIO_APROBACION <", value, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionLessThanOrEqualTo(String value) {
			addCriterion("ANIO_APROBACION <=", value, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionLike(String value) {
			addCriterion("ANIO_APROBACION like", value, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionNotLike(String value) {
			addCriterion("ANIO_APROBACION not like", value, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionIn(List values) {
			addCriterion("ANIO_APROBACION in", values, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionNotIn(List values) {
			addCriterion("ANIO_APROBACION not in", values, "anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionBetween(String value1, String value2) {
			addCriterion("ANIO_APROBACION between", value1, value2,
					"anioAprobacion");
			return this;
		}

		public Criteria andAnioAprobacionNotBetween(String value1, String value2) {
			addCriterion("ANIO_APROBACION not between", value1, value2,
					"anioAprobacion");
			return this;
		}

		public Criteria andNoAprobacionIsNull() {
			addCriterion("NO_APROBACION is null");
			return this;
		}

		public Criteria andNoAprobacionIsNotNull() {
			addCriterion("NO_APROBACION is not null");
			return this;
		}

		public Criteria andNoAprobacionEqualTo(String value) {
			addCriterion("NO_APROBACION =", value, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionNotEqualTo(String value) {
			addCriterion("NO_APROBACION <>", value, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionGreaterThan(String value) {
			addCriterion("NO_APROBACION >", value, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionGreaterThanOrEqualTo(String value) {
			addCriterion("NO_APROBACION >=", value, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionLessThan(String value) {
			addCriterion("NO_APROBACION <", value, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionLessThanOrEqualTo(String value) {
			addCriterion("NO_APROBACION <=", value, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionLike(String value) {
			addCriterion("NO_APROBACION like", value, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionNotLike(String value) {
			addCriterion("NO_APROBACION not like", value, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionIn(List values) {
			addCriterion("NO_APROBACION in", values, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionNotIn(List values) {
			addCriterion("NO_APROBACION not in", values, "noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionBetween(String value1, String value2) {
			addCriterion("NO_APROBACION between", value1, value2,
					"noAprobacion");
			return this;
		}

		public Criteria andNoAprobacionNotBetween(String value1, String value2) {
			addCriterion("NO_APROBACION not between", value1, value2,
					"noAprobacion");
			return this;
		}
	}
}