package mx.com.factmex.app.server.sqlmaps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TUsuarioExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public TUsuarioExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected TUsuarioExample(TUsuarioExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdUsuarioIsNull() {
			addCriterion("ID_USUARIO is null");
			return this;
		}

		public Criteria andIdUsuarioIsNotNull() {
			addCriterion("ID_USUARIO is not null");
			return this;
		}

		public Criteria andIdUsuarioEqualTo(String value) {
			addCriterion("ID_USUARIO =", value, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioNotEqualTo(String value) {
			addCriterion("ID_USUARIO <>", value, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioGreaterThan(String value) {
			addCriterion("ID_USUARIO >", value, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioGreaterThanOrEqualTo(String value) {
			addCriterion("ID_USUARIO >=", value, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioLessThan(String value) {
			addCriterion("ID_USUARIO <", value, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioLessThanOrEqualTo(String value) {
			addCriterion("ID_USUARIO <=", value, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioLike(String value) {
			addCriterion("ID_USUARIO like", value, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioNotLike(String value) {
			addCriterion("ID_USUARIO not like", value, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioIn(List values) {
			addCriterion("ID_USUARIO in", values, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioNotIn(List values) {
			addCriterion("ID_USUARIO not in", values, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioBetween(String value1, String value2) {
			addCriterion("ID_USUARIO between", value1, value2, "idUsuario");
			return this;
		}

		public Criteria andIdUsuarioNotBetween(String value1, String value2) {
			addCriterion("ID_USUARIO not between", value1, value2, "idUsuario");
			return this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("NOMBRE is null");
			return this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("NOMBRE is not null");
			return this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("NOMBRE =", value, "nombre");
			return this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("NOMBRE <>", value, "nombre");
			return this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("NOMBRE >", value, "nombre");
			return this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE >=", value, "nombre");
			return this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("NOMBRE <", value, "nombre");
			return this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE <=", value, "nombre");
			return this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("NOMBRE like", value, "nombre");
			return this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("NOMBRE not like", value, "nombre");
			return this;
		}

		public Criteria andNombreIn(List values) {
			addCriterion("NOMBRE in", values, "nombre");
			return this;
		}

		public Criteria andNombreNotIn(List values) {
			addCriterion("NOMBRE not in", values, "nombre");
			return this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("NOMBRE between", value1, value2, "nombre");
			return this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("NOMBRE not between", value1, value2, "nombre");
			return this;
		}

		public Criteria andApellidosIsNull() {
			addCriterion("APELLIDOS is null");
			return this;
		}

		public Criteria andApellidosIsNotNull() {
			addCriterion("APELLIDOS is not null");
			return this;
		}

		public Criteria andApellidosEqualTo(String value) {
			addCriterion("APELLIDOS =", value, "apellidos");
			return this;
		}

		public Criteria andApellidosNotEqualTo(String value) {
			addCriterion("APELLIDOS <>", value, "apellidos");
			return this;
		}

		public Criteria andApellidosGreaterThan(String value) {
			addCriterion("APELLIDOS >", value, "apellidos");
			return this;
		}

		public Criteria andApellidosGreaterThanOrEqualTo(String value) {
			addCriterion("APELLIDOS >=", value, "apellidos");
			return this;
		}

		public Criteria andApellidosLessThan(String value) {
			addCriterion("APELLIDOS <", value, "apellidos");
			return this;
		}

		public Criteria andApellidosLessThanOrEqualTo(String value) {
			addCriterion("APELLIDOS <=", value, "apellidos");
			return this;
		}

		public Criteria andApellidosLike(String value) {
			addCriterion("APELLIDOS like", value, "apellidos");
			return this;
		}

		public Criteria andApellidosNotLike(String value) {
			addCriterion("APELLIDOS not like", value, "apellidos");
			return this;
		}

		public Criteria andApellidosIn(List values) {
			addCriterion("APELLIDOS in", values, "apellidos");
			return this;
		}

		public Criteria andApellidosNotIn(List values) {
			addCriterion("APELLIDOS not in", values, "apellidos");
			return this;
		}

		public Criteria andApellidosBetween(String value1, String value2) {
			addCriterion("APELLIDOS between", value1, value2, "apellidos");
			return this;
		}

		public Criteria andApellidosNotBetween(String value1, String value2) {
			addCriterion("APELLIDOS not between", value1, value2, "apellidos");
			return this;
		}

		public Criteria andUsuarioIsNull() {
			addCriterion("USUARIO is null");
			return this;
		}

		public Criteria andUsuarioIsNotNull() {
			addCriterion("USUARIO is not null");
			return this;
		}

		public Criteria andUsuarioEqualTo(String value) {
			addCriterion("USUARIO =", value, "usuario");
			return this;
		}

		public Criteria andUsuarioNotEqualTo(String value) {
			addCriterion("USUARIO <>", value, "usuario");
			return this;
		}

		public Criteria andUsuarioGreaterThan(String value) {
			addCriterion("USUARIO >", value, "usuario");
			return this;
		}

		public Criteria andUsuarioGreaterThanOrEqualTo(String value) {
			addCriterion("USUARIO >=", value, "usuario");
			return this;
		}

		public Criteria andUsuarioLessThan(String value) {
			addCriterion("USUARIO <", value, "usuario");
			return this;
		}

		public Criteria andUsuarioLessThanOrEqualTo(String value) {
			addCriterion("USUARIO <=", value, "usuario");
			return this;
		}

		public Criteria andUsuarioLike(String value) {
			addCriterion("USUARIO like", value, "usuario");
			return this;
		}

		public Criteria andUsuarioNotLike(String value) {
			addCriterion("USUARIO not like", value, "usuario");
			return this;
		}

		public Criteria andUsuarioIn(List values) {
			addCriterion("USUARIO in", values, "usuario");
			return this;
		}

		public Criteria andUsuarioNotIn(List values) {
			addCriterion("USUARIO not in", values, "usuario");
			return this;
		}

		public Criteria andUsuarioBetween(String value1, String value2) {
			addCriterion("USUARIO between", value1, value2, "usuario");
			return this;
		}

		public Criteria andUsuarioNotBetween(String value1, String value2) {
			addCriterion("USUARIO not between", value1, value2, "usuario");
			return this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return this;
		}

		public Criteria andPasswordIn(List values) {
			addCriterion("PASSWORD in", values, "password");
			return this;
		}

		public Criteria andPasswordNotIn(List values) {
			addCriterion("PASSWORD not in", values, "password");
			return this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return this;
		}

		public Criteria andFechaFinIsNull() {
			addCriterion("FECHA_FIN is null");
			return this;
		}

		public Criteria andFechaFinIsNotNull() {
			addCriterion("FECHA_FIN is not null");
			return this;
		}

		public Criteria andFechaFinEqualTo(String value) {
			addCriterion("FECHA_FIN =", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotEqualTo(String value) {
			addCriterion("FECHA_FIN <>", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinGreaterThan(String value) {
			addCriterion("FECHA_FIN >", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinGreaterThanOrEqualTo(String value) {
			addCriterion("FECHA_FIN >=", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinLessThan(String value) {
			addCriterion("FECHA_FIN <", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinLessThanOrEqualTo(String value) {
			addCriterion("FECHA_FIN <=", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinLike(String value) {
			addCriterion("FECHA_FIN like", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotLike(String value) {
			addCriterion("FECHA_FIN not like", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinIn(List values) {
			addCriterion("FECHA_FIN in", values, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotIn(List values) {
			addCriterion("FECHA_FIN not in", values, "fechaFin");
			return this;
		}

		public Criteria andFechaFinBetween(String value1, String value2) {
			addCriterion("FECHA_FIN between", value1, value2, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotBetween(String value1, String value2) {
			addCriterion("FECHA_FIN not between", value1, value2, "fechaFin");
			return this;
		}

		public Criteria andIdPerfilIsNull() {
			addCriterion("ID_PERFIL is null");
			return this;
		}

		public Criteria andIdPerfilIsNotNull() {
			addCriterion("ID_PERFIL is not null");
			return this;
		}

		public Criteria andIdPerfilEqualTo(String value) {
			addCriterion("ID_PERFIL =", value, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilNotEqualTo(String value) {
			addCriterion("ID_PERFIL <>", value, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilGreaterThan(String value) {
			addCriterion("ID_PERFIL >", value, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilGreaterThanOrEqualTo(String value) {
			addCriterion("ID_PERFIL >=", value, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilLessThan(String value) {
			addCriterion("ID_PERFIL <", value, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilLessThanOrEqualTo(String value) {
			addCriterion("ID_PERFIL <=", value, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilLike(String value) {
			addCriterion("ID_PERFIL like", value, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilNotLike(String value) {
			addCriterion("ID_PERFIL not like", value, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilIn(List values) {
			addCriterion("ID_PERFIL in", values, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilNotIn(List values) {
			addCriterion("ID_PERFIL not in", values, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilBetween(String value1, String value2) {
			addCriterion("ID_PERFIL between", value1, value2, "idPerfil");
			return this;
		}

		public Criteria andIdPerfilNotBetween(String value1, String value2) {
			addCriterion("ID_PERFIL not between", value1, value2, "idPerfil");
			return this;
		}

		public Criteria andIdEmisorIsNull() {
			addCriterion("ID_EMISOR is null");
			return this;
		}

		public Criteria andIdEmisorIsNotNull() {
			addCriterion("ID_EMISOR is not null");
			return this;
		}

		public Criteria andIdEmisorEqualTo(String value) {
			addCriterion("ID_EMISOR =", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotEqualTo(String value) {
			addCriterion("ID_EMISOR <>", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThan(String value) {
			addCriterion("ID_EMISOR >", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorGreaterThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR >=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThan(String value) {
			addCriterion("ID_EMISOR <", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLessThanOrEqualTo(String value) {
			addCriterion("ID_EMISOR <=", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorLike(String value) {
			addCriterion("ID_EMISOR like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotLike(String value) {
			addCriterion("ID_EMISOR not like", value, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorIn(List values) {
			addCriterion("ID_EMISOR in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotIn(List values) {
			addCriterion("ID_EMISOR not in", values, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorBetween(String value1, String value2) {
			addCriterion("ID_EMISOR between", value1, value2, "idEmisor");
			return this;
		}

		public Criteria andIdEmisorNotBetween(String value1, String value2) {
			addCriterion("ID_EMISOR not between", value1, value2, "idEmisor");
			return this;
		}
	}
}