package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.CCompania;
import mx.com.factmex.app.server.sqlmaps.model.CCompaniaExample;

public class CCompaniaDAOImpl implements CCompaniaDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CCompaniaDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int countByExample(CCompaniaExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"C_COMPANIA.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByExample(CCompaniaExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"C_COMPANIA.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByPrimaryKey(String idCompania) throws SQLException {
		CCompania key = new CCompania();
		key.setIdCompania(idCompania);
		int rows = sqlMapClient.delete(
				"C_COMPANIA.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insert(CCompania record) throws SQLException {
		sqlMapClient.insert("C_COMPANIA.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insertSelective(CCompania record) throws SQLException {
		sqlMapClient.insert("C_COMPANIA.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List selectByExample(CCompaniaExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"C_COMPANIA.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CCompania selectByPrimaryKey(String idCompania) throws SQLException {
		CCompania key = new CCompania();
		key.setIdCompania(idCompania);
		CCompania record = (CCompania) sqlMapClient.queryForObject(
				"C_COMPANIA.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExampleSelective(CCompania record,
			CCompaniaExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_COMPANIA.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExample(CCompania record, CCompaniaExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_COMPANIA.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKeySelective(CCompania record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"C_COMPANIA.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKey(CCompania record) throws SQLException {
		int rows = sqlMapClient.update(
				"C_COMPANIA.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table C_COMPANIA
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private static class UpdateByExampleParms extends CCompaniaExample {
		private Object record;

		public UpdateByExampleParms(Object record, CCompaniaExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}