package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.CEstatus;
import mx.com.factmex.app.server.sqlmaps.model.CEstatusExample;

public class CEstatusDAOImpl implements CEstatusDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CEstatusDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int countByExample(CEstatusExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"C_ESTATUS.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByExample(CEstatusExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"C_ESTATUS.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByPrimaryKey(String idEstatus) throws SQLException {
		CEstatus key = new CEstatus();
		key.setIdEstatus(idEstatus);
		int rows = sqlMapClient.delete(
				"C_ESTATUS.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insert(CEstatus record) throws SQLException {
		sqlMapClient.insert("C_ESTATUS.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insertSelective(CEstatus record) throws SQLException {
		sqlMapClient
				.insert("C_ESTATUS.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List selectByExample(CEstatusExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"C_ESTATUS.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CEstatus selectByPrimaryKey(String idEstatus) throws SQLException {
		CEstatus key = new CEstatus();
		key.setIdEstatus(idEstatus);
		CEstatus record = (CEstatus) sqlMapClient.queryForObject(
				"C_ESTATUS.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExampleSelective(CEstatus record, CEstatusExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_ESTATUS.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExample(CEstatus record, CEstatusExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_ESTATUS.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKeySelective(CEstatus record) throws SQLException {
		int rows = sqlMapClient
				.update("C_ESTATUS.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKey(CEstatus record) throws SQLException {
		int rows = sqlMapClient.update(
				"C_ESTATUS.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table C_ESTATUS
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private static class UpdateByExampleParms extends CEstatusExample {
		private Object record;

		public UpdateByExampleParms(Object record, CEstatusExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}