package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.CParametro;
import mx.com.factmex.app.server.sqlmaps.model.CParametroExample;

public class CParametroDAOImpl implements CParametroDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CParametroDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int countByExample(CParametroExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"C_PARAMETRO.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByExample(CParametroExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"C_PARAMETRO.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByPrimaryKey(String idParametro) throws SQLException {
		CParametro key = new CParametro();
		key.setIdParametro(idParametro);
		int rows = sqlMapClient.delete(
				"C_PARAMETRO.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insert(CParametro record) throws SQLException {
		sqlMapClient.insert("C_PARAMETRO.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insertSelective(CParametro record) throws SQLException {
		sqlMapClient.insert("C_PARAMETRO.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List selectByExample(CParametroExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"C_PARAMETRO.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CParametro selectByPrimaryKey(String idParametro)
			throws SQLException {
		CParametro key = new CParametro();
		key.setIdParametro(idParametro);
		CParametro record = (CParametro) sqlMapClient.queryForObject(
				"C_PARAMETRO.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExampleSelective(CParametro record,
			CParametroExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_PARAMETRO.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExample(CParametro record, CParametroExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_PARAMETRO.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKeySelective(CParametro record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"C_PARAMETRO.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKey(CParametro record) throws SQLException {
		int rows = sqlMapClient.update(
				"C_PARAMETRO.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table C_PARAMETRO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private static class UpdateByExampleParms extends CParametroExample {
		private Object record;

		public UpdateByExampleParms(Object record, CParametroExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}