package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.CPerfil;
import mx.com.factmex.app.server.sqlmaps.model.CPerfilExample;

public class CPerfilDAOImpl implements CPerfilDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CPerfilDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int countByExample(CPerfilExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"C_PERFIL.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByExample(CPerfilExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"C_PERFIL.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByPrimaryKey(String idPerfil) throws SQLException {
		CPerfil key = new CPerfil();
		key.setIdPerfil(idPerfil);
		int rows = sqlMapClient.delete(
				"C_PERFIL.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insert(CPerfil record) throws SQLException {
		sqlMapClient.insert("C_PERFIL.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insertSelective(CPerfil record) throws SQLException {
		sqlMapClient.insert("C_PERFIL.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List selectByExample(CPerfilExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"C_PERFIL.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CPerfil selectByPrimaryKey(String idPerfil) throws SQLException {
		CPerfil key = new CPerfil();
		key.setIdPerfil(idPerfil);
		CPerfil record = (CPerfil) sqlMapClient.queryForObject(
				"C_PERFIL.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExampleSelective(CPerfil record, CPerfilExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_PERFIL.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExample(CPerfil record, CPerfilExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_PERFIL.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKeySelective(CPerfil record) throws SQLException {
		int rows = sqlMapClient.update(
				"C_PERFIL.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKey(CPerfil record) throws SQLException {
		int rows = sqlMapClient.update(
				"C_PERFIL.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private static class UpdateByExampleParms extends CPerfilExample {
		private Object record;

		public UpdateByExampleParms(Object record, CPerfilExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}