package mx.com.factmex.app.server.sqlmaps.dao;

import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.CPerfil;
import mx.com.factmex.app.server.sqlmaps.model.CPerfilExample;

public interface CPerfilDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int countByExample(CPerfilExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int deleteByExample(CPerfilExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int deleteByPrimaryKey(String idPerfil) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	void insert(CPerfil record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	void insertSelective(CPerfil record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	List selectByExample(CPerfilExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	CPerfil selectByPrimaryKey(String idPerfil) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByExampleSelective(CPerfil record, CPerfilExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByExample(CPerfil record, CPerfilExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByPrimaryKeySelective(CPerfil record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_PERFIL
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByPrimaryKey(CPerfil record) throws SQLException;
}