package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.CTipoComprobante;
import mx.com.factmex.app.server.sqlmaps.model.CTipoComprobanteExample;

public class CTipoComprobanteDAOImpl implements CTipoComprobanteDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CTipoComprobanteDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int countByExample(CTipoComprobanteExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"C_TIPO_COMPROBANTE.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByExample(CTipoComprobanteExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"C_TIPO_COMPROBANTE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByPrimaryKey(String idTipoComprobante) throws SQLException {
		CTipoComprobante key = new CTipoComprobante();
		key.setIdTipoComprobante(idTipoComprobante);
		int rows = sqlMapClient.delete(
				"C_TIPO_COMPROBANTE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insert(CTipoComprobante record) throws SQLException {
		sqlMapClient
				.insert("C_TIPO_COMPROBANTE.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insertSelective(CTipoComprobante record) throws SQLException {
		sqlMapClient.insert(
				"C_TIPO_COMPROBANTE.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List selectByExample(CTipoComprobanteExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"C_TIPO_COMPROBANTE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public CTipoComprobante selectByPrimaryKey(String idTipoComprobante)
			throws SQLException {
		CTipoComprobante key = new CTipoComprobante();
		key.setIdTipoComprobante(idTipoComprobante);
		CTipoComprobante record = (CTipoComprobante) sqlMapClient
				.queryForObject(
						"C_TIPO_COMPROBANTE.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExampleSelective(CTipoComprobante record,
			CTipoComprobanteExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_TIPO_COMPROBANTE.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExample(CTipoComprobante record,
			CTipoComprobanteExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"C_TIPO_COMPROBANTE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKeySelective(CTipoComprobante record)
			throws SQLException {
		int rows = sqlMapClient
				.update("C_TIPO_COMPROBANTE.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKey(CTipoComprobante record) throws SQLException {
		int rows = sqlMapClient
				.update("C_TIPO_COMPROBANTE.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table C_TIPO_COMPROBANTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private static class UpdateByExampleParms extends CTipoComprobanteExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				CTipoComprobanteExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}