package mx.com.factmex.app.server.sqlmaps.dao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.CTipoContacto;
import mx.com.factmex.app.server.sqlmaps.model.CTipoContactoExample;

public interface CTipoContactoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int countByExample(CTipoContactoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int deleteByExample(CTipoContactoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int deleteByPrimaryKey(String idTipoContacto) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	void insert(CTipoContacto record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	void insertSelective(CTipoContacto record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	List selectByExample(CTipoContactoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	CTipoContacto selectByPrimaryKey(String idTipoContacto) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByExampleSelective(CTipoContacto record,
			CTipoContactoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByExample(CTipoContacto record, CTipoContactoExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByPrimaryKeySelective(CTipoContacto record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table C_TIPO_CONTACTO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByPrimaryKey(CTipoContacto record) throws SQLException;
}