package mx.com.factmex.app.server.sqlmaps.dao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.TCliente;
import mx.com.factmex.app.server.sqlmaps.model.TClienteExample;

public interface TClienteDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int countByExample(TClienteExample example) throws SQLException;

	int maxIdCliente() throws SQLException;
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int deleteByExample(TClienteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int deleteByPrimaryKey(String idCliente) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	void insert(TCliente record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	void insertSelective(TCliente record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	List selectByExample(TClienteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	TCliente selectByPrimaryKey(String idCliente) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByExampleSelective(TCliente record, TClienteExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByExample(TCliente record, TClienteExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByPrimaryKeySelective(TCliente record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	int updateByPrimaryKey(TCliente record) throws SQLException;
}