package mx.com.factmex.app.server.sqlmaps.dao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.TComprobante;
import mx.com.factmex.app.server.sqlmaps.model.TComprobanteExample;

public interface TComprobanteDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	int countByExample(TComprobanteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	int deleteByExample(TComprobanteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	int deleteByPrimaryKey(String idFactura) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	void insert(TComprobante record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	void insertSelective(TComprobante record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	List selectByExample(TComprobanteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	TComprobante selectByPrimaryKey(String idFactura) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	int updateByExampleSelective(TComprobante record,
			TComprobanteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	int updateByExample(TComprobante record, TComprobanteExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	int updateByPrimaryKeySelective(TComprobante record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	int updateByPrimaryKey(TComprobante record) throws SQLException;

	int maxIdComprobante() throws SQLException;

}