package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.TComprobante;
import mx.com.factmex.app.server.sqlmaps.model.TComprobanteExample;

public class TComprobanteDAOImpl implements TComprobanteDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public TComprobanteDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public int countByExample(TComprobanteExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"T_COMPROBANTE.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public int deleteByExample(TComprobanteExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"T_COMPROBANTE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public int deleteByPrimaryKey(String idFactura) throws SQLException {
		TComprobante key = new TComprobante();
		key.setIdFactura(idFactura);
		int rows = sqlMapClient.delete(
				"T_COMPROBANTE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void insert(TComprobante record) throws SQLException {
		sqlMapClient.insert("T_COMPROBANTE.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public void insertSelective(TComprobante record) throws SQLException {
		sqlMapClient.insert("T_COMPROBANTE.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public List selectByExample(TComprobanteExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"T_COMPROBANTE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public TComprobante selectByPrimaryKey(String idFactura)
			throws SQLException {
		TComprobante key = new TComprobante();
		key.setIdFactura(idFactura);
		TComprobante record = (TComprobante) sqlMapClient.queryForObject(
				"T_COMPROBANTE.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public int updateByExampleSelective(TComprobante record,
			TComprobanteExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("T_COMPROBANTE.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public int updateByExample(TComprobante record, TComprobanteExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"T_COMPROBANTE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public int updateByPrimaryKeySelective(TComprobante record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"T_COMPROBANTE.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	public int updateByPrimaryKey(TComprobante record) throws SQLException {
		int rows = sqlMapClient.update(
				"T_COMPROBANTE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_COMPROBANTE
	 * @ibatorgenerated  Wed Nov 10 10:37:30 CST 2010
	 */
	private static class UpdateByExampleParms extends TComprobanteExample {
		private Object record;

		public UpdateByExampleParms(Object record, TComprobanteExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_CLIENTE
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int maxIdComprobante() throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"T_COMPROBANTE.ibatorgenerated_maxIdComprobante");
		return count.intValue();
	}
}