package mx.com.factmex.app.server.sqlmaps.dao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.TEmisor;
import mx.com.factmex.app.server.sqlmaps.model.TEmisorExample;

public interface TEmisorDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	int countByExample(TEmisorExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	int deleteByExample(TEmisorExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	int deleteByPrimaryKey(String idEmisor) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	void insert(TEmisor record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	void insertSelective(TEmisor record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	List selectByExample(TEmisorExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	TEmisor selectByPrimaryKey(String idEmisor) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	int updateByExampleSelective(TEmisor record, TEmisorExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	int updateByExample(TEmisor record, TEmisorExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	int updateByPrimaryKeySelective(TEmisor record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_EMISOR
	 * @ibatorgenerated  Fri Oct 22 15:57:18 CDT 2010
	 */
	int updateByPrimaryKey(TEmisor record) throws SQLException;
}