package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.TProductoServicio;
import mx.com.factmex.app.server.sqlmaps.model.TProductoServicioExample;

public class TProductoServicioDAOImpl implements TProductoServicioDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public TProductoServicioDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int countByExample(TProductoServicioExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"T_PRODUCTO_SERVICIO.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByExample(TProductoServicioExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"T_PRODUCTO_SERVICIO.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByPrimaryKey(String idProductoServicio)
			throws SQLException {
		TProductoServicio key = new TProductoServicio();
		key.setIdProductoServicio(idProductoServicio);
		int rows = sqlMapClient.delete(
				"T_PRODUCTO_SERVICIO.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insert(TProductoServicio record) throws SQLException {
		sqlMapClient.insert("T_PRODUCTO_SERVICIO.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insertSelective(TProductoServicio record) throws SQLException {
		sqlMapClient.insert(
				"T_PRODUCTO_SERVICIO.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List selectByExample(TProductoServicioExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"T_PRODUCTO_SERVICIO.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public TProductoServicio selectByPrimaryKey(String idProductoServicio)
			throws SQLException {
		TProductoServicio key = new TProductoServicio();
		key.setIdProductoServicio(idProductoServicio);
		TProductoServicio record = (TProductoServicio) sqlMapClient
				.queryForObject(
						"T_PRODUCTO_SERVICIO.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExampleSelective(TProductoServicio record,
			TProductoServicioExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"T_PRODUCTO_SERVICIO.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExample(TProductoServicio record,
			TProductoServicioExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"T_PRODUCTO_SERVICIO.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKeySelective(TProductoServicio record)
			throws SQLException {
		int rows = sqlMapClient
				.update("T_PRODUCTO_SERVICIO.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKey(TProductoServicio record) throws SQLException {
		int rows = sqlMapClient.update(
				"T_PRODUCTO_SERVICIO.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_PRODUCTO_SERVICIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private static class UpdateByExampleParms extends TProductoServicioExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TProductoServicioExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}