package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.TSerie;
import mx.com.factmex.app.server.sqlmaps.model.TSerieExample;

public class TSerieDAOImpl implements TSerieDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public TSerieDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public int countByExample(TSerieExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"T_SERIE.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public int deleteByExample(TSerieExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"T_SERIE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public int deleteByPrimaryKey(String idSerie) throws SQLException {
		TSerie key = new TSerie();
		key.setIdSerie(idSerie);
		int rows = sqlMapClient.delete(
				"T_SERIE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void insert(TSerie record) throws SQLException {
		sqlMapClient.insert("T_SERIE.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public void insertSelective(TSerie record) throws SQLException {
		sqlMapClient.insert("T_SERIE.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public List selectByExample(TSerieExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"T_SERIE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public TSerie selectByPrimaryKey(String idSerie) throws SQLException {
		TSerie key = new TSerie();
		key.setIdSerie(idSerie);
		TSerie record = (TSerie) sqlMapClient.queryForObject(
				"T_SERIE.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public int updateByExampleSelective(TSerie record, TSerieExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"T_SERIE.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public int updateByExample(TSerie record, TSerieExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"T_SERIE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public int updateByPrimaryKeySelective(TSerie record) throws SQLException {
		int rows = sqlMapClient.update(
				"T_SERIE.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	public int updateByPrimaryKey(TSerie record) throws SQLException {
		int rows = sqlMapClient.update(
				"T_SERIE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	private static class UpdateByExampleParms extends TSerieExample {
		private Object record;

		public UpdateByExampleParms(Object record, TSerieExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}