package mx.com.factmex.app.server.sqlmaps.dao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.TSerie;
import mx.com.factmex.app.server.sqlmaps.model.TSerieExample;

public interface TSerieDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	int countByExample(TSerieExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	int deleteByExample(TSerieExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	int deleteByPrimaryKey(String idSerie) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	void insert(TSerie record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	void insertSelective(TSerie record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	List selectByExample(TSerieExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	TSerie selectByPrimaryKey(String idSerie) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	int updateByExampleSelective(TSerie record, TSerieExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	int updateByExample(TSerie record, TSerieExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	int updateByPrimaryKeySelective(TSerie record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_SERIE
	 * @ibatorgenerated  Tue Oct 26 17:22:55 CDT 2010
	 */
	int updateByPrimaryKey(TSerie record) throws SQLException;
}