package mx.com.factmex.app.server.sqlmaps.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import mx.com.factmex.app.server.sqlmaps.model.TUsuario;
import mx.com.factmex.app.server.sqlmaps.model.TUsuarioExample;

public class TUsuarioDAOImpl implements TUsuarioDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public TUsuarioDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int countByExample(TUsuarioExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"T_USUARIO.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByExample(TUsuarioExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"T_USUARIO.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int deleteByPrimaryKey(String idUsuario) throws SQLException {
		TUsuario key = new TUsuario();
		key.setIdUsuario(idUsuario);
		int rows = sqlMapClient.delete(
				"T_USUARIO.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insert(TUsuario record) throws SQLException {
		sqlMapClient.insert("T_USUARIO.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public void insertSelective(TUsuario record) throws SQLException {
		sqlMapClient
				.insert("T_USUARIO.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public List selectByExample(TUsuarioExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"T_USUARIO.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public TUsuario selectByPrimaryKey(String idUsuario) throws SQLException {
		TUsuario key = new TUsuario();
		key.setIdUsuario(idUsuario);
		TUsuario record = (TUsuario) sqlMapClient.queryForObject(
				"T_USUARIO.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExampleSelective(TUsuario record, TUsuarioExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"T_USUARIO.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByExample(TUsuario record, TUsuarioExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"T_USUARIO.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKeySelective(TUsuario record) throws SQLException {
		int rows = sqlMapClient
				.update("T_USUARIO.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	public int updateByPrimaryKey(TUsuario record) throws SQLException {
		int rows = sqlMapClient.update(
				"T_USUARIO.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table T_USUARIO
	 * @ibatorgenerated  Tue Oct 19 12:54:15 CDT 2010
	 */
	private static class UpdateByExampleParms extends TUsuarioExample {
		private Object record;

		public UpdateByExampleParms(Object record, TUsuarioExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}